-- TRANSACTIONS (Payment History)
CREATE TABLE IF NOT EXISTS public.transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) NOT NULL,
  event_id BIGINT REFERENCES public.events(id) ON DELETE SET NULL,
  ticket_id BIGINT REFERENCES public.tickets(id) ON DELETE SET NULL,
  amount NUMERIC(10, 2) NOT NULL,
  currency TEXT DEFAULT 'TZS',
  provider TEXT NOT NULL, -- 'AzamPay', 'Stripe', etc.
  provider_transaction_id TEXT, -- ID from payment provider
  status TEXT DEFAULT 'pending', -- 'pending', 'success', 'failed', 'refunded'
  metadata JSONB DEFAULT '{}'::jsonb, -- Store extra provider response data
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

-- Users can see their own transactions
CREATE POLICY "Users can view own transactions" ON public.transactions
  FOR SELECT USING (auth.uid() = user_id);

-- Users can insert pending transactions (initial intent)
CREATE POLICY "Users can insert pending transactions" ON public.transactions
  FOR INSERT WITH CHECK (auth.uid() = user_id AND status = 'pending');

-- Only allow service role (backend) to update status to success/failed usually,
-- but for simplicity in development we might not strictly block updates yet,
-- though strictly we should. We'll leave update policy restricted or rely on service_role.
-- (No update policy for public users means they can't change status after creation)
