-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- PROFILES (Public profiles for users)
create table public.profiles (
  id uuid references auth.users not null primary key,
  username text unique,
  full_name text,
  avatar_url text,
  bio text,
  is_organizer boolean default false,
  verified boolean default false,
  location text,
  cover_url text,
  organizer_type text, -- e.g., 'Club', 'Festival', 'Individual'
  phone text,
  website text,
  social_links jsonb default '{}'::jsonb, -- { instagram: '', facebook: '', twitter: '' }
  contact_email text,
  notification_settings jsonb default '{"emailNotifications": true, "pushNotifications": true, "eventReminders": true, "ticketSales": true, "newFollowers": true, "streamAlerts": true, "weeklyReport": true, "marketingEmails": false}'::jsonb,
  streaming_settings jsonb default '{"defaultQuality": "1080p", "autoRecord": true, "chatEnabled": true, "reactionsEnabled": true, "multiCamera": false, "lowLatency": true}'::jsonb,
  privacy_settings jsonb default '{"profileVisibility": "public", "showEmail": false, "showPhone": false, "allowMessages": true, "showFollowers": true, "showStats": true}'::jsonb,
  payment_settings jsonb default '{"paymentMethod": "bank"}'::jsonb,
  preferences jsonb default '{}'::jsonb, -- Generic user preferences (e.g. recent searches)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- EVENTS
create table public.events (
  id bigint generated by default as identity primary key,
  organizer_id uuid references public.profiles(id) not null,
  title text not null,
  description text,
  date date not null,
  time time not null,
  location text not null,
  city text, -- 'dar', 'zanzibar', 'atlanta', 'newyork', etc.
  category text not null,
  subcategory text,
  price_range text, -- Display text like "TSh 20,000 - 50,000"
  image_url text,
  views integer default 0,
  status text default 'published', -- 'published', 'draft', 'cancelled'
  
  -- JSONB columns for structured data
  streaming jsonb default '{}'::jsonb, 
  -- Structure: { available: boolean, quality: string, virtualPrice: string, isLive: boolean, liveViewers: number, replayAvailable: boolean, features: string[], playback_url: string }
  
  ticket_tiers jsonb default '[]'::jsonb,
  -- Structure: [{ name: string, price: string, priceNumeric: number, available: number, features: string[], color: string }]
  
  event_highlights jsonb default '[]'::jsonb,
  -- Structure: [{ image: string, video: string, caption: string, type: string, mediaType: string }]
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- TICKETS (Purchased tickets)
create table public.tickets (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  event_id bigint references public.events(id) not null,
  ticket_number text not null unique,
  barcode text not null, -- Could be same as ticket_number or separate
  price text not null,
  purchase_date timestamp with time zone default timezone('utc'::text, now()) not null,
  customer_name text not null,
  customer_email text not null,
  ticket_type text not null, -- 'Normal', 'VIP', 'VVIP'
  status text default 'valid', -- 'valid', 'used', 'refunded'
  qr_code text
);

-- SAVED EVENTS
create table public.saved_events (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  event_id bigint references public.events(id) not null,
  is_reminder boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, event_id)
);

-- FOLLOWS
create table public.follows (
  id bigint generated by default as identity primary key,
  follower_id uuid references public.profiles(id) not null,
  following_id uuid references public.profiles(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(follower_id, following_id)
);

-- POSTS (Social feed)
create table public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  event_id bigint references public.events(id), -- Optional link to an event
  content text,
  image_urls text[] default '{}',
  video_url text,
  duration text, -- For video duration display
  views integer default 0,
  hashtags text[] default '{}',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- POST LIKES
create table public.post_likes (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  post_id bigint references public.posts(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, post_id)
);

-- POST COMMENTS
create table public.post_comments (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  post_id bigint references public.posts(id) not null,
  text text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- SAVED POSTS
create table public.saved_posts (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  post_id bigint references public.posts(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, post_id)
);

-- CONVERSATIONS (Direct Messaging)
create table public.conversations (
  id bigint generated by default as identity primary key,
  participant1_id uuid references public.profiles(id) not null,
  participant2_id uuid references public.profiles(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(participant1_id, participant2_id)
);

-- MESSAGES (DM content)
create table public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint references public.conversations(id) not null,
  sender_id uuid references public.profiles(id) not null,
  content text not null,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- STREAM CHAT MESSAGES (Live stream chat)
create table public.stream_chat_messages (
  id bigint generated by default as identity primary key,
  event_id bigint references public.events(id) not null,
  user_id uuid references public.profiles(id) not null,
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- USER MEDIA (Gallery/Portfolio)
create table public.user_media (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  media_type text not null, -- 'photo', 'video'
  url text not null,
  thumbnail_url text,
  caption text,
  likes integer default 0,
  views integer default 0,
  duration text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ROW LEVEL SECURITY (RLS) POLICIES
-- Enable RLS on all tables
alter table profiles enable row level security;
alter table events enable row level security;
alter table tickets enable row level security;
alter table saved_events enable row level security;
alter table follows enable row level security;
alter table posts enable row level security;
alter table post_likes enable row level security;
alter table post_comments enable row level security;
alter table saved_posts enable row level security;
alter table conversations enable row level security;
alter table messages enable row level security;
alter table stream_chat_messages enable row level security;
alter table user_media enable row level security;

-- PROFILES Policies
create policy "Public profiles are viewable by everyone" on profiles for select using (true);
create policy "Users can insert their own profile" on profiles for insert with check (auth.uid() = id);
create policy "Users can update their own profile" on profiles for update using (auth.uid() = id);

-- EVENTS Policies
create policy "Events are viewable by everyone" on events for select using (true);
create policy "Organizers can insert events" on events for insert with check (auth.uid() = organizer_id);
create policy "Organizers can update their own events" on events for update using (auth.uid() = organizer_id);
create policy "Organizers can delete their own events" on events for delete using (auth.uid() = organizer_id);

-- TICKETS Policies
create policy "Users can view their own tickets" on tickets for select using (auth.uid() = user_id);
create policy "Organizers can view tickets for their events" on tickets for select using (
  exists (select 1 from events where events.id = tickets.event_id and events.organizer_id = auth.uid())
);
create policy "Users can insert tickets (purchase)" on tickets for insert with check (auth.uid() = user_id);

-- SAVED EVENTS Policies
create policy "Users can view their own saved events" on saved_events for select using (auth.uid() = user_id);
create policy "Users can manage their own saved events" on saved_events for all using (auth.uid() = user_id);

-- FOLLOWS Policies
create policy "Follows are viewable by everyone" on follows for select using (true);
create policy "Users can manage their own follows" on follows for all using (auth.uid() = follower_id);

-- POSTS Policies
create policy "Posts are viewable by everyone" on posts for select using (true);
create policy "Users can insert posts" on posts for insert with check (auth.uid() = user_id);
create policy "Users can update their own posts" on posts for update using (auth.uid() = user_id);
create policy "Users can delete their own posts" on posts for delete using (auth.uid() = user_id);

-- POST LIKES/COMMENTS/SAVES Policies
create policy "Public interactions viewable by everyone" on post_likes for select using (true);
create policy "Users manage own likes" on post_likes for all using (auth.uid() = user_id);

create policy "Public comments viewable by everyone" on post_comments for select using (true);
create policy "Users manage own comments" on post_comments for all using (auth.uid() = user_id);

create policy "Users manage own saved posts" on saved_posts for all using (auth.uid() = user_id);

-- CONVERSATIONS/MESSAGES Policies
create policy "Users can view their conversations" on conversations for select using (
  auth.uid() = participant1_id or auth.uid() = participant2_id
);
create policy "Users can insert conversations" on conversations for insert with check (
  auth.uid() = participant1_id or auth.uid() = participant2_id
);

create policy "Users can view messages in their conversations" on messages for select using (
  exists (
    select 1 from conversations 
    where conversations.id = messages.conversation_id 
    and (conversations.participant1_id = auth.uid() or conversations.participant2_id = auth.uid())
  )
);
create policy "Users can insert messages" on messages for insert with check (auth.uid() = sender_id);
create policy "Users can update messages (mark read)" on messages for update using (
  exists (
    select 1 from conversations 
    where conversations.id = messages.conversation_id 
    and (conversations.participant1_id = auth.uid() or conversations.participant2_id = auth.uid())
  )
);

-- STREAM CHAT Policies
create policy "Stream chat is viewable by everyone" on stream_chat_messages for select using (true);
create policy "Users can insert stream chat messages" on stream_chat_messages for insert with check (auth.uid() = user_id);

-- USER MEDIA Policies
create policy "User media is viewable by everyone" on user_media for select using (true);
create policy "Users can manage their own media" on user_media for all using (auth.uid() = user_id);

-- TRIGGERS for updated_at
create or replace function update_updated_at_column()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

create trigger update_profiles_updated_at before update on profiles for each row execute procedure update_updated_at_column();
create trigger update_events_updated_at before update on events for each row execute procedure update_updated_at_column();
create trigger update_conversations_updated_at before update on conversations for each row execute procedure update_updated_at_column();