-- Consolidated Eventz Supabase schema.
-- Built from every SQL migration in supabase/migrations and supabase/migrations/archive,
-- with project/runtime objects included where the app expects them.
--
-- Intended for a fresh Supabase project. Review carefully before running against
-- a populated database, because it represents the final schema state rather than
-- the historical step-by-step data transformations.

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
BEGIN
  CREATE TYPE public.app_role AS ENUM ('admin', 'moderator', 'user');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- ---------------------------------------------------------------------------
-- Core tables
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT,
  username TEXT UNIQUE,
  full_name TEXT,
  avatar_url TEXT,
  bio TEXT,
  birthdate DATE,
  location TEXT,
  is_organizer BOOLEAN DEFAULT false,
  verified BOOLEAN DEFAULT false,
  cover_url TEXT,
  organizer_type TEXT,
  description TEXT,
  contact_email TEXT,
  phone TEXT,
  website TEXT,
  social_links JSONB DEFAULT '{}'::jsonb,
  preferences JSONB DEFAULT '{}'::jsonb,
  streaming_settings JSONB DEFAULT '{}'::jsonb,
  privacy_settings JSONB DEFAULT '{}'::jsonb,
  notification_settings JSONB DEFAULT '{}'::jsonb,
  payment_settings JSONB DEFAULT '{}'::jsonb,
  last_notification_read_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.organizer_profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  organizer_name TEXT,
  organizer_type TEXT,
  avatar_url TEXT,
  organizer_avatar_url TEXT,
  cover_url TEXT,
  bio TEXT,
  description TEXT,
  location TEXT,
  website TEXT,
  contact_email TEXT,
  phone TEXT,
  social_links JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organizer_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  date DATE NOT NULL,
  time TIME,
  location TEXT NOT NULL,
  city TEXT,
  category TEXT NOT NULL,
  subcategory TEXT,
  price TEXT,
  price_range TEXT,
  image_url TEXT,
  attendees INTEGER DEFAULT 0,
  views INTEGER DEFAULT 0,
  status TEXT DEFAULT 'published',
  streaming JSONB,
  ticket_tiers JSONB,
  event_highlights JSONB,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  event_id BIGINT REFERENCES public.events(id) ON DELETE SET NULL,
  content TEXT,
  image_urls TEXT[],
  hashtags TEXT[],
  video_url TEXT,
  duration TEXT,
  views INTEGER DEFAULT 0,
  posted_as_organizer BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  text TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (post_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  actor_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  read BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.saved_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  event_id BIGINT NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
  is_reminder BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, event_id)
);

CREATE TABLE IF NOT EXISTS public.saved_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  post_id BIGINT NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, post_id)
);

CREATE TABLE IF NOT EXISTS public.post_likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (post_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.post_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  parent_id BIGINT REFERENCES public.post_comments(id) ON DELETE CASCADE,
  text TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.comment_likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comment_id BIGINT NOT NULL REFERENCES public.post_comments(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (comment_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.event_likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (event_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.follows (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  follower_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  following_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (follower_id, following_id),
  CHECK (follower_id <> following_id)
);

CREATE TABLE IF NOT EXISTS public.user_media (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  event_id BIGINT REFERENCES public.events(id) ON DELETE SET NULL,
  url TEXT NOT NULL,
  media_type TEXT NOT NULL,
  thumbnail_url TEXT,
  caption TEXT,
  duration TEXT,
  views INTEGER DEFAULT 0,
  likes INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  event_id BIGINT NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
  ticket_type TEXT NOT NULL,
  price TEXT NOT NULL,
  ticket_number TEXT NOT NULL,
  barcode TEXT NOT NULL,
  customer_name TEXT NOT NULL,
  customer_email TEXT NOT NULL,
  qr_code TEXT,
  purchase_date TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  created_at TIMESTAMPTZ DEFAULT now(),
  status TEXT DEFAULT 'valid',
  scanned_at TIMESTAMPTZ,
  scanned_by UUID REFERENCES auth.users(id)
);

CREATE TABLE IF NOT EXISTS public.transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  event_id BIGINT REFERENCES public.events(id) ON DELETE SET NULL,
  ticket_id BIGINT REFERENCES public.tickets(id) ON DELETE SET NULL,
  amount NUMERIC(10, 2) NOT NULL,
  currency TEXT DEFAULT 'TZS',
  provider TEXT NOT NULL,
  provider_transaction_id TEXT,
  status TEXT DEFAULT 'pending',
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.stream_chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  participant1_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  participant2_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (participant1_id, participant2_id),
  CHECK (participant1_id <> participant2_id)
);

CREATE TABLE IF NOT EXISTS public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE,
  sender_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  image_url TEXT,
  is_read BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.cloudflare_streams (
  id BIGSERIAL PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  event_id BIGINT REFERENCES public.events(id) ON DELETE SET NULL,
  uid TEXT NOT NULL UNIQUE,
  live_input_uid TEXT,
  title TEXT NOT NULL DEFAULT 'Streamed video',
  thumbnail_url TEXT,
  preview_url TEXT,
  playback_url TEXT,
  duration NUMERIC,
  status TEXT,
  raw_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.user_roles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role public.app_role NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (user_id, role)
);

CREATE TABLE IF NOT EXISTS public.audit_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  admin_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  target_type TEXT,
  target_id TEXT,
  old_value JSONB,
  new_value JSONB,
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.feature_flags (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  key TEXT NOT NULL UNIQUE,
  enabled BOOLEAN DEFAULT false,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  reporter_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  content_type TEXT NOT NULL,
  content_id TEXT NOT NULL,
  reason TEXT NOT NULL,
  status TEXT DEFAULT 'pending',
  resolution_note TEXT,
  resolved_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_events_organizer_id ON public.events(organizer_id);
CREATE INDEX IF NOT EXISTS idx_events_status_date ON public.events(status, date);
CREATE INDEX IF NOT EXISTS idx_posts_user_id ON public.posts(user_id);
CREATE INDEX IF NOT EXISTS idx_posts_event_id ON public.posts(event_id);
CREATE INDEX IF NOT EXISTS idx_post_likes_post_id ON public.post_likes(post_id);
CREATE INDEX IF NOT EXISTS idx_post_likes_user_id ON public.post_likes(user_id);
CREATE INDEX IF NOT EXISTS idx_post_comments_post_id ON public.post_comments(post_id);
CREATE INDEX IF NOT EXISTS idx_post_comments_user_id ON public.post_comments(user_id);
CREATE INDEX IF NOT EXISTS idx_comment_likes_comment_id ON public.comment_likes(comment_id);
CREATE INDEX IF NOT EXISTS idx_event_likes_event_id ON public.event_likes(event_id);
CREATE INDEX IF NOT EXISTS idx_saved_events_user_id ON public.saved_events(user_id);
CREATE INDEX IF NOT EXISTS idx_saved_events_event_id ON public.saved_events(event_id);
CREATE INDEX IF NOT EXISTS idx_saved_posts_user_id ON public.saved_posts(user_id);
CREATE INDEX IF NOT EXISTS idx_saved_posts_post_id ON public.saved_posts(post_id);
CREATE INDEX IF NOT EXISTS idx_follows_follower_id ON public.follows(follower_id);
CREATE INDEX IF NOT EXISTS idx_follows_following_id ON public.follows(following_id);
CREATE INDEX IF NOT EXISTS idx_tickets_user_id ON public.tickets(user_id);
CREATE INDEX IF NOT EXISTS idx_tickets_event_id ON public.tickets(event_id);
CREATE INDEX IF NOT EXISTS idx_tickets_purchase_date ON public.tickets(purchase_date);
CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON public.messages(conversation_id);
CREATE INDEX IF NOT EXISTS idx_messages_sender_id ON public.messages(sender_id);
CREATE INDEX IF NOT EXISTS idx_stream_chat_messages_event_id ON public.stream_chat_messages(event_id);
CREATE INDEX IF NOT EXISTS idx_organizer_profiles_id ON public.organizer_profiles(id);
CREATE INDEX IF NOT EXISTS cloudflare_streams_user_id_created_at_idx
  ON public.cloudflare_streams(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS cloudflare_streams_event_id_idx
  ON public.cloudflare_streams(event_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_user_id ON public.user_roles(user_id);
CREATE INDEX IF NOT EXISTS idx_reports_status_created_at ON public.reports(status, created_at DESC);

-- ---------------------------------------------------------------------------
-- Utility and trigger functions
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, avatar_url)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'name', NEW.raw_user_meta_data->>'full_name'),
    NEW.raw_user_meta_data->>'avatar_url'
  )
  ON CONFLICT (id) DO UPDATE
  SET
    email = EXCLUDED.email,
    full_name = COALESCE(public.profiles.full_name, EXCLUDED.full_name),
    avatar_url = COALESCE(public.profiles.avatar_url, EXCLUDED.avatar_url);

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.check_profile_updates()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  v_bypass TEXT;
BEGIN
  BEGIN
    v_bypass := current_setting('app.bypass_profile_trigger', true);
  EXCEPTION WHEN OTHERS THEN
    v_bypass := 'false';
  END;

  IF v_bypass = 'true' THEN
    RETURN NEW;
  END IF;

  IF (NEW.is_organizer IS DISTINCT FROM OLD.is_organizer)
     OR (NEW.verified IS DISTINCT FROM OLD.verified) THEN
    RAISE EXCEPTION 'Unauthorized: You cannot update privileged profile fields directly.';
  END IF;

  IF (NEW.organizer_type IS DISTINCT FROM OLD.organizer_type) THEN
    IF auth.uid() IS NULL OR auth.uid() <> OLD.id OR COALESCE(OLD.is_organizer, false) <> true THEN
      RAISE EXCEPTION 'Unauthorized: You cannot update privileged profile fields directly.';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.update_event_attendees_count()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    UPDATE public.events
    SET attendees = (SELECT count(*) FROM public.tickets WHERE event_id = NEW.event_id)
    WHERE id = NEW.event_id;
    RETURN NEW;
  ELSIF (TG_OP = 'DELETE') THEN
    UPDATE public.events
    SET attendees = (SELECT count(*) FROM public.tickets WHERE event_id = OLD.event_id)
    WHERE id = OLD.event_id;
    RETURN OLD;
  ELSIF (TG_OP = 'UPDATE') THEN
    IF OLD.event_id IS DISTINCT FROM NEW.event_id THEN
      UPDATE public.events
      SET attendees = (SELECT count(*) FROM public.tickets WHERE event_id = OLD.event_id)
      WHERE id = OLD.event_id;

      UPDATE public.events
      SET attendees = (SELECT count(*) FROM public.tickets WHERE event_id = NEW.event_id)
      WHERE id = NEW.event_id;
    END IF;
    RETURN NEW;
  END IF;

  RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.handle_new_message()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.conversations
  SET updated_at = now()
  WHERE id = NEW.conversation_id;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.has_role(_user_id UUID, _role public.app_role)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.user_roles
    WHERE user_id = _user_id
      AND role = _role
  );
$$;

-- ---------------------------------------------------------------------------
-- RPC functions
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.become_organizer(
  p_full_name TEXT,
  p_username TEXT,
  p_organizer_type TEXT,
  p_location TEXT,
  p_bio TEXT,
  p_avatar_url TEXT,
  p_contact_email TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id UUID;
  v_result JSONB;
BEGIN
  v_user_id := auth.uid();

  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE username = p_username
      AND id <> v_user_id
  ) THEN
    RAISE EXCEPTION 'Username already taken';
  END IF;

  PERFORM set_config('app.bypass_profile_trigger', 'true', true);

  UPDATE public.profiles
  SET
    full_name = p_full_name,
    username = p_username,
    organizer_type = p_organizer_type,
    location = p_location,
    bio = p_bio,
    avatar_url = p_avatar_url,
    contact_email = COALESCE(p_contact_email, contact_email),
    is_organizer = true,
    updated_at = now()
  WHERE id = v_user_id
  RETURNING to_jsonb(public.profiles.*) INTO v_result;

  PERFORM set_config('app.bypass_profile_trigger', 'false', true);

  RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION public.downgrade_to_personal_account()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  current_user_id UUID;
BEGIN
  current_user_id := auth.uid();

  IF current_user_id IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  PERFORM set_config('app.bypass_profile_trigger', 'true', true);

  UPDATE public.profiles
  SET is_organizer = false,
      updated_at = now()
  WHERE id = current_user_id;

  PERFORM set_config('app.bypass_profile_trigger', 'false', true);
END;
$$;

CREATE OR REPLACE FUNCTION public.purchase_ticket(
  p_event_id BIGINT,
  p_ticket_type TEXT,
  p_customer_name TEXT,
  p_customer_email TEXT,
  p_ticket_number TEXT,
  p_qr_code TEXT,
  p_user_id UUID DEFAULT NULL,
  p_price TEXT DEFAULT NULL,
  p_transaction_id BIGINT DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_ticket_tiers JSONB;
  v_new_ticket_id BIGINT;
  v_updated_tiers JSONB;
  v_available_count INT;
  v_tier_found BOOLEAN := false;
  v_event_base_price TEXT;
  v_final_user_id UUID;
  v_event_price TEXT;
  v_required_amount NUMERIC;
  v_tx_status TEXT;
  v_tx_amount NUMERIC;
  v_tx_user UUID;
  v_tx_ticket_id BIGINT;
  v_tier JSONB;
BEGIN
  v_final_user_id := COALESCE(p_user_id, auth.uid());

  IF v_final_user_id IS NULL THEN
    RAISE EXCEPTION 'User must be logged in';
  END IF;

  IF p_transaction_id IS NULL THEN
    RAISE EXCEPTION 'Transaction id required';
  END IF;

  SELECT ticket_tiers, price
  INTO v_ticket_tiers, v_event_base_price
  FROM public.events
  WHERE id = p_event_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Event not found';
  END IF;

  IF v_ticket_tiers IS NOT NULL AND jsonb_array_length(v_ticket_tiers) > 0 THEN
    FOR v_tier IN SELECT * FROM jsonb_array_elements(v_ticket_tiers)
    LOOP
      IF v_tier->>'name' = p_ticket_type THEN
        v_event_price := v_tier->>'price';
        v_tier_found := true;

        IF v_tier ? 'available' THEN
          v_available_count := (v_tier->>'available')::int;
          IF v_available_count <= 0 THEN
            RAISE EXCEPTION 'Tickets sold out for this tier';
          END IF;
        END IF;

        EXIT;
      END IF;
    END LOOP;

    IF NOT v_tier_found THEN
      RAISE EXCEPTION 'Invalid ticket type';
    END IF;

    SELECT jsonb_agg(
      CASE
        WHEN elem->>'name' = p_ticket_type AND (elem ? 'available') THEN
          jsonb_set(elem, '{available}', ((elem->>'available')::int - 1)::text::jsonb)
        ELSE elem
      END
    )
    INTO v_updated_tiers
    FROM jsonb_array_elements(v_ticket_tiers) AS elem;

    UPDATE public.events
    SET ticket_tiers = v_updated_tiers
    WHERE id = p_event_id;
  ELSE
    v_event_price := COALESCE(v_event_base_price, p_price, '0');
  END IF;

  v_required_amount := NULLIF(regexp_replace(COALESCE(v_event_price, '0'), '[^0-9\.]', '', 'g'), '')::numeric;
  IF v_required_amount IS NULL THEN
    v_required_amount := 0;
  END IF;

  SELECT status, amount, user_id, ticket_id
  INTO v_tx_status, v_tx_amount, v_tx_user, v_tx_ticket_id
  FROM public.transactions
  WHERE id = p_transaction_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Transaction not found';
  END IF;

  IF v_tx_user IS DISTINCT FROM v_final_user_id THEN
    RAISE EXCEPTION 'Transaction does not belong to user';
  END IF;

  IF v_tx_ticket_id IS NOT NULL THEN
    RAISE EXCEPTION 'Transaction already used';
  END IF;

  IF lower(coalesce(v_tx_status, '')) NOT IN ('completed', 'success') THEN
    RAISE EXCEPTION 'Transaction not completed';
  END IF;

  IF v_tx_amount < v_required_amount THEN
    RAISE EXCEPTION 'Insufficient transaction amount';
  END IF;

  INSERT INTO public.tickets (
    user_id,
    event_id,
    ticket_number,
    barcode,
    price,
    purchase_date,
    customer_name,
    customer_email,
    ticket_type,
    status,
    qr_code
  )
  VALUES (
    v_final_user_id,
    p_event_id,
    p_ticket_number,
    p_ticket_number,
    v_event_price,
    now(),
    p_customer_name,
    p_customer_email,
    p_ticket_type,
    'valid',
    p_qr_code
  )
  RETURNING id INTO v_new_ticket_id;

  UPDATE public.transactions
  SET ticket_id = v_new_ticket_id,
      updated_at = now()
  WHERE id = p_transaction_id;

  RETURN json_build_object('id', v_new_ticket_id, 'status', 'success');
END;
$$;

CREATE OR REPLACE FUNCTION public.purchase_ticket(
  p_event_id BIGINT,
  p_ticket_type TEXT,
  p_customer_name TEXT,
  p_customer_email TEXT,
  p_ticket_number TEXT,
  p_qr_code TEXT,
  p_user_id UUID DEFAULT NULL,
  p_price TEXT DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_event_price TEXT;
  v_ticket_tiers JSONB;
  v_new_ticket_id BIGINT;
  v_updated_tiers JSONB;
  v_available_count INT;
  v_tier_found BOOLEAN := false;
  v_event_base_price TEXT;
  v_final_user_id UUID;
  v_tier JSONB;
BEGIN
  v_final_user_id := COALESCE(p_user_id, auth.uid());

  IF v_final_user_id IS NULL THEN
    RAISE EXCEPTION 'User must be logged in or user_id provided';
  END IF;

  SELECT ticket_tiers, price
  INTO v_ticket_tiers, v_event_base_price
  FROM public.events
  WHERE id = p_event_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Event not found';
  END IF;

  IF v_ticket_tiers IS NOT NULL AND jsonb_array_length(v_ticket_tiers) > 0 THEN
    FOR v_tier IN SELECT * FROM jsonb_array_elements(v_ticket_tiers)
    LOOP
      IF v_tier->>'name' = p_ticket_type THEN
        v_event_price := v_tier->>'price';
        v_tier_found := true;

        IF v_tier ? 'available' THEN
          v_available_count := (v_tier->>'available')::int;
          IF v_available_count <= 0 THEN
            RAISE EXCEPTION 'Tickets sold out for this tier';
          END IF;
        END IF;

        EXIT;
      END IF;
    END LOOP;

    IF NOT v_tier_found THEN
      RAISE EXCEPTION 'Invalid ticket type or ticket type not found for this event';
    END IF;

    SELECT jsonb_agg(
      CASE
        WHEN elem->>'name' = p_ticket_type AND (elem ? 'available') THEN
          jsonb_set(elem, '{available}', ((elem->>'available')::int - 1)::text::jsonb)
        ELSE elem
      END
    )
    INTO v_updated_tiers
    FROM jsonb_array_elements(v_ticket_tiers) AS elem;

    UPDATE public.events
    SET ticket_tiers = v_updated_tiers
    WHERE id = p_event_id;
  ELSE
    v_event_price := COALESCE(v_event_base_price, p_price, '0');
  END IF;

  INSERT INTO public.tickets (
    user_id,
    event_id,
    ticket_number,
    barcode,
    price,
    purchase_date,
    customer_name,
    customer_email,
    ticket_type,
    status,
    qr_code
  )
  VALUES (
    v_final_user_id,
    p_event_id,
    p_ticket_number,
    p_ticket_number,
    v_event_price,
    now(),
    p_customer_name,
    p_customer_email,
    p_ticket_type,
    'valid',
    p_qr_code
  )
  RETURNING id INTO v_new_ticket_id;

  RETURN json_build_object('id', v_new_ticket_id, 'status', 'success');
END;
$$;

CREATE OR REPLACE FUNCTION public.purchase_ticket(
  p_event_id BIGINT,
  p_ticket_type TEXT,
  p_customer_name TEXT,
  p_customer_email TEXT,
  p_ticket_number TEXT,
  p_qr_code TEXT
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_event_price TEXT;
  v_ticket_tiers JSONB;
  v_new_ticket_id BIGINT;
  v_updated_tiers JSONB;
  v_available_count INT;
  v_tier_found BOOLEAN := false;
  v_event_base_price TEXT;
  v_tier JSONB;
BEGIN
  SELECT ticket_tiers, price
  INTO v_ticket_tiers, v_event_base_price
  FROM public.events
  WHERE id = p_event_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Event not found';
  END IF;

  IF v_ticket_tiers IS NOT NULL AND jsonb_array_length(v_ticket_tiers) > 0 THEN
    FOR v_tier IN SELECT * FROM jsonb_array_elements(v_ticket_tiers)
    LOOP
      IF v_tier->>'name' = p_ticket_type THEN
        v_event_price := v_tier->>'price';
        v_tier_found := true;

        IF v_tier ? 'available' THEN
          v_available_count := (v_tier->>'available')::int;
          IF v_available_count <= 0 THEN
            RAISE EXCEPTION 'Tickets sold out for this tier';
          END IF;
        END IF;

        EXIT;
      END IF;
    END LOOP;

    IF NOT v_tier_found THEN
      RAISE EXCEPTION 'Invalid ticket type or ticket type not found for this event';
    END IF;

    SELECT jsonb_agg(
      CASE
        WHEN elem->>'name' = p_ticket_type AND (elem ? 'available') THEN
          jsonb_set(elem, '{available}', ((elem->>'available')::int - 1)::text::jsonb)
        ELSE elem
      END
    )
    INTO v_updated_tiers
    FROM jsonb_array_elements(v_ticket_tiers) AS elem;

    UPDATE public.events
    SET ticket_tiers = v_updated_tiers
    WHERE id = p_event_id;
  ELSE
    v_event_price := COALESCE(v_event_base_price, '0');
  END IF;

  INSERT INTO public.tickets (
    user_id,
    event_id,
    ticket_number,
    barcode,
    price,
    purchase_date,
    customer_name,
    customer_email,
    ticket_type,
    status,
    qr_code
  )
  VALUES (
    auth.uid(),
    p_event_id,
    p_ticket_number,
    p_ticket_number,
    v_event_price,
    now(),
    p_customer_name,
    p_customer_email,
    p_ticket_type,
    'valid',
    p_qr_code
  )
  RETURNING id INTO v_new_ticket_id;

  RETURN json_build_object('id', v_new_ticket_id, 'status', 'success');
END;
$$;

CREATE OR REPLACE FUNCTION public.scan_ticket(
  p_ticket_code TEXT,
  p_event_id BIGINT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_ticket RECORD;
  v_event RECORD;
  v_user_id UUID;
BEGIN
  v_user_id := auth.uid();

  SELECT * INTO v_event
  FROM public.events
  WHERE id = p_event_id;

  IF v_event IS NULL THEN
    RETURN jsonb_build_object('success', false, 'message', 'Event not found');
  END IF;

  IF v_event.organizer_id <> v_user_id THEN
    RETURN jsonb_build_object('success', false, 'message', 'Unauthorized: You are not the organizer of this event');
  END IF;

  SELECT * INTO v_ticket
  FROM public.tickets
  WHERE event_id = p_event_id
    AND (barcode = p_ticket_code OR ticket_number = p_ticket_code);

  IF v_ticket IS NULL THEN
    RETURN jsonb_build_object('success', false, 'message', 'Invalid Ticket: Ticket not found for this event');
  END IF;

  IF v_ticket.status = 'used' OR v_ticket.scanned_at IS NOT NULL THEN
    RETURN jsonb_build_object(
      'success', false,
      'message', 'Already Scanned',
      'data', jsonb_build_object(
        'scanned_at', v_ticket.scanned_at,
        'customer_name', v_ticket.customer_name,
        'ticket_type', v_ticket.ticket_type
      )
    );
  END IF;

  IF v_ticket.status <> 'valid' AND v_ticket.status <> 'active' THEN
    RETURN jsonb_build_object('success', false, 'message', 'Invalid Ticket: Status is ' || v_ticket.status);
  END IF;

  UPDATE public.tickets
  SET status = 'used',
      scanned_at = now(),
      scanned_by = v_user_id
  WHERE id = v_ticket.id;

  RETURN jsonb_build_object(
    'success', true,
    'message', 'Ticket Verified',
    'data', jsonb_build_object(
      'customer_name', v_ticket.customer_name,
      'ticket_type', v_ticket.ticket_type,
      'ticket_number', v_ticket.ticket_number
    )
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.delete_event_complete(target_event_id BIGINT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM public.events
    WHERE id = target_event_id
      AND organizer_id = auth.uid()
  ) THEN
    RAISE EXCEPTION 'Not authorized to delete this event';
  END IF;

  UPDATE public.posts
  SET event_id = NULL
  WHERE event_id = target_event_id;

  DELETE FROM public.stream_chat_messages WHERE event_id = target_event_id;
  DELETE FROM public.saved_events WHERE event_id = target_event_id;
  DELETE FROM public.tickets WHERE event_id = target_event_id;
  DELETE FROM public.events WHERE id = target_event_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.increment_event_view(event_id BIGINT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.events
  SET views = COALESCE(views, 0) + 1
  WHERE id = event_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.increment_post_view(post_id BIGINT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.posts
  SET views = COALESCE(views, 0) + 1
  WHERE id = post_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.increment_media_view(media_id BIGINT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.user_media
  SET views = COALESCE(views, 0) + 1
  WHERE id = media_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_organizer_stats(target_user_id UUID)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_total_events BIGINT;
  v_followers BIGINT;
  v_event_views BIGINT;
  v_post_views BIGINT;
  v_media_views BIGINT;
  v_total_views BIGINT;
  v_live_streams BIGINT;
  v_tickets_sold BIGINT;
  v_revenue BIGINT;
BEGIN
  SELECT count(*) INTO v_total_events
  FROM public.events
  WHERE organizer_id = target_user_id;

  SELECT count(*) INTO v_followers
  FROM public.follows
  WHERE following_id = target_user_id;

  SELECT COALESCE(sum(views), 0) INTO v_event_views
  FROM public.events
  WHERE organizer_id = target_user_id;

  SELECT COALESCE(sum(views), 0) INTO v_post_views
  FROM public.posts
  WHERE user_id = target_user_id;

  SELECT COALESCE(sum(views), 0) INTO v_media_views
  FROM public.user_media
  WHERE user_id = target_user_id;

  v_total_views := v_event_views + v_post_views + v_media_views;

  SELECT count(*) INTO v_live_streams
  FROM public.events
  WHERE organizer_id = target_user_id
    AND (streaming->>'available')::boolean IS true;

  SELECT
    count(*),
    COALESCE(sum(
      CASE
        WHEN t.price IS NULL OR t.price = 'Free' THEN 0
        ELSE COALESCE(NULLIF(regexp_replace(t.price, '[^0-9]', '', 'g'), '')::integer, 0)
      END
    ), 0)
  INTO v_tickets_sold, v_revenue
  FROM public.tickets t
  JOIN public.events e ON t.event_id = e.id
  WHERE e.organizer_id = target_user_id;

  RETURN json_build_object(
    'totalEvents', v_total_events,
    'followers', v_followers,
    'totalViews', v_total_views,
    'ticketsSold', v_tickets_sold,
    'revenue', v_revenue,
    'liveStreams', v_live_streams,
    'avgRating', 0
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.get_event_analytics(target_event_id BIGINT)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_views BIGINT;
  v_interested_count BIGINT;
  v_tickets_sold BIGINT;
  v_shares_count BIGINT;
  v_revenue BIGINT;
  v_interested_last_7 BIGINT;
  v_interested_prev_7 BIGINT;
  v_tickets_last_7 BIGINT;
  v_tickets_prev_7 BIGINT;
  v_shares_last_7 BIGINT;
  v_shares_prev_7 BIGINT;
  v_daily_activity INTEGER[];
  v_location_counts json;
  v_age_counts json;
BEGIN
  SELECT views INTO v_views
  FROM public.events
  WHERE id = target_event_id;

  SELECT count(*) INTO v_interested_count
  FROM public.saved_events
  WHERE event_id = target_event_id;

  SELECT count(*) INTO v_shares_count
  FROM public.posts
  WHERE event_id = target_event_id;

  SELECT
    count(*),
    COALESCE(sum(
      CASE
        WHEN price IS NULL OR price = 'Free' THEN 0
        ELSE COALESCE(NULLIF(regexp_replace(price, '[^0-9]', '', 'g'), '')::integer, 0)
      END
    ), 0)
  INTO v_tickets_sold, v_revenue
  FROM public.tickets
  WHERE event_id = target_event_id;

  SELECT
    count(*) FILTER (WHERE created_at >= now() - interval '7 days'),
    count(*) FILTER (WHERE created_at >= now() - interval '14 days' AND created_at < now() - interval '7 days')
  INTO v_interested_last_7, v_interested_prev_7
  FROM public.saved_events
  WHERE event_id = target_event_id;

  SELECT
    count(*) FILTER (WHERE created_at >= now() - interval '7 days'),
    count(*) FILTER (WHERE created_at >= now() - interval '14 days' AND created_at < now() - interval '7 days')
  INTO v_tickets_last_7, v_tickets_prev_7
  FROM public.tickets
  WHERE event_id = target_event_id;

  SELECT
    count(*) FILTER (WHERE created_at >= now() - interval '7 days'),
    count(*) FILTER (WHERE created_at >= now() - interval '14 days' AND created_at < now() - interval '7 days')
  INTO v_shares_last_7, v_shares_prev_7
  FROM public.posts
  WHERE event_id = target_event_id;

  WITH activity AS (
    SELECT created_at FROM public.saved_events WHERE event_id = target_event_id AND created_at >= now() - interval '7 days'
    UNION ALL
    SELECT created_at FROM public.tickets WHERE event_id = target_event_id AND created_at >= now() - interval '7 days'
    UNION ALL
    SELECT created_at FROM public.posts WHERE event_id = target_event_id AND created_at >= now() - interval '7 days'
  )
  SELECT array_agg(d)
  INTO v_daily_activity
  FROM (
    SELECT count(a.created_at)::integer AS d
    FROM generate_series(0, 6) AS day_idx
    LEFT JOIN activity a
      ON (EXTRACT(ISODOW FROM a.created_at)::int - 1) = day_idx
    GROUP BY day_idx
    ORDER BY day_idx
  ) t;

  IF v_daily_activity IS NULL THEN
    v_daily_activity := ARRAY[0,0,0,0,0,0,0];
  END IF;

  WITH unique_users AS (
    SELECT user_id FROM public.tickets WHERE event_id = target_event_id
    UNION
    SELECT user_id FROM public.saved_events WHERE event_id = target_event_id
  ),
  user_locs AS (
    SELECT split_part(p.location, ',', 1) AS city
    FROM unique_users u
    JOIN public.profiles p ON u.user_id = p.id
    WHERE p.location IS NOT NULL AND p.location <> ''
  )
  SELECT json_object_agg(city, count)
  INTO v_location_counts
  FROM (
    SELECT city, count(*) AS count
    FROM user_locs
    GROUP BY city
    ORDER BY count DESC
    LIMIT 5
  ) t;

  WITH unique_users AS (
    SELECT user_id FROM public.tickets WHERE event_id = target_event_id
    UNION
    SELECT user_id FROM public.saved_events WHERE event_id = target_event_id
  ),
  user_ages AS (
    SELECT EXTRACT(YEAR FROM AGE(current_date, p.birthdate)) AS age
    FROM unique_users u
    JOIN public.profiles p ON u.user_id = p.id
    WHERE p.birthdate IS NOT NULL
  )
  SELECT json_build_object(
    '18-24', count(*) FILTER (WHERE age BETWEEN 18 AND 24),
    '25-34', count(*) FILTER (WHERE age BETWEEN 25 AND 34),
    '35-44', count(*) FILTER (WHERE age BETWEEN 35 AND 44),
    '45+', count(*) FILTER (WHERE age >= 45)
  )
  INTO v_age_counts
  FROM user_ages;

  RETURN json_build_object(
    'views', COALESCE(v_views, 0),
    'interested', v_interested_count,
    'ticketsSold', v_tickets_sold,
    'shares', v_shares_count,
    'revenue', v_revenue,
    'trends', json_build_object(
      'interested', json_build_object('last7', v_interested_last_7, 'prev7', v_interested_prev_7),
      'tickets', json_build_object('last7', v_tickets_last_7, 'prev7', v_tickets_prev_7),
      'shares', json_build_object('last7', v_shares_last_7, 'prev7', v_shares_prev_7)
    ),
    'dailyActivity', v_daily_activity,
    'demographics', json_build_object(
      'locations', COALESCE(v_location_counts, '{}'::json),
      'ageGroups', COALESCE(v_age_counts, json_build_object('18-24', 0, '25-34', 0, '35-44', 0, '45+', 0))
    )
  );
END;
$$;

-- ---------------------------------------------------------------------------
-- Triggers
-- ---------------------------------------------------------------------------

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

DROP TRIGGER IF EXISTS protect_profile_fields ON public.profiles;
CREATE TRIGGER protect_profile_fields
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.check_profile_updates();

DROP TRIGGER IF EXISTS update_profiles_updated_at ON public.profiles;
CREATE TRIGGER update_profiles_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_events_updated_at ON public.events;
CREATE TRIGGER update_events_updated_at
  BEFORE UPDATE ON public.events
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS on_ticket_change ON public.tickets;
CREATE TRIGGER on_ticket_change
  AFTER INSERT OR DELETE OR UPDATE OF event_id ON public.tickets
  FOR EACH ROW EXECUTE FUNCTION public.update_event_attendees_count();

DROP TRIGGER IF EXISTS on_message_created ON public.messages;
CREATE TRIGGER on_message_created
  AFTER INSERT ON public.messages
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_message();

DROP TRIGGER IF EXISTS update_conversations_updated_at ON public.conversations;
CREATE TRIGGER update_conversations_updated_at
  BEFORE UPDATE ON public.conversations
  FOR EACH ROW EXECUTE PROCEDURE public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_cloudflare_streams_updated_at ON public.cloudflare_streams;
CREATE TRIGGER update_cloudflare_streams_updated_at
  BEFORE UPDATE ON public.cloudflare_streams
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_feature_flags_updated_at ON public.feature_flags;
CREATE TRIGGER update_feature_flags_updated_at
  BEFORE UPDATE ON public.feature_flags
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_reports_updated_at ON public.reports;
CREATE TRIGGER update_reports_updated_at
  BEFORE UPDATE ON public.reports
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ---------------------------------------------------------------------------
-- Row level security and policies
-- ---------------------------------------------------------------------------

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organizer_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.saved_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.saved_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comment_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.follows ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_media ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stream_chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cloudflare_streams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feature_flags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public profiles are viewable by everyone" ON public.profiles;
CREATE POLICY "Public profiles are viewable by everyone"
  ON public.profiles FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Users can insert their own profile" ON public.profiles;
CREATE POLICY "Users can insert their own profile"
  ON public.profiles FOR INSERT
  WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update own profile (safe)" ON public.profiles;
CREATE POLICY "Users can update own profile (safe)"
  ON public.profiles FOR UPDATE
  USING (auth.uid() = id)
  WITH CHECK (
    auth.uid() = id
    AND is_organizer IS NOT DISTINCT FROM (SELECT p.is_organizer FROM public.profiles p WHERE p.id = auth.uid())
    AND verified IS NOT DISTINCT FROM (SELECT p.verified FROM public.profiles p WHERE p.id = auth.uid())
  );

DROP POLICY IF EXISTS "Public profiles are viewable by everyone" ON public.organizer_profiles;
CREATE POLICY "Public profiles are viewable by everyone"
  ON public.organizer_profiles FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Organizers can insert their own profile" ON public.organizer_profiles;
CREATE POLICY "Organizers can insert their own profile"
  ON public.organizer_profiles FOR INSERT
  WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Organizers can update their own profile" ON public.organizer_profiles;
CREATE POLICY "Organizers can update their own profile"
  ON public.organizer_profiles FOR UPDATE
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Events are viewable by everyone" ON public.events;
CREATE POLICY "Events are viewable by everyone"
  ON public.events FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Organizers can insert events" ON public.events;
CREATE POLICY "Organizers can insert events"
  ON public.events FOR INSERT
  WITH CHECK (
    auth.uid() = organizer_id
    AND EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid()
        AND p.is_organizer = true
    )
  );

DROP POLICY IF EXISTS "Organizers can update own events" ON public.events;
CREATE POLICY "Organizers can update own events"
  ON public.events FOR UPDATE
  USING (auth.uid() = organizer_id)
  WITH CHECK (
    auth.uid() = organizer_id
    AND EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid()
        AND p.is_organizer = true
    )
  );

DROP POLICY IF EXISTS "Posts are viewable by everyone" ON public.posts;
CREATE POLICY "Posts are viewable by everyone"
  ON public.posts FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Users can insert posts" ON public.posts;
CREATE POLICY "Users can insert posts"
  ON public.posts FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own posts" ON public.posts;
CREATE POLICY "Users can update own posts"
  ON public.posts FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own posts" ON public.posts;
CREATE POLICY "Users can delete their own posts"
  ON public.posts FOR DELETE
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Comments are viewable by everyone" ON public.comments;
CREATE POLICY "Comments are viewable by everyone"
  ON public.comments FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Authenticated users can comment" ON public.comments;
CREATE POLICY "Authenticated users can comment"
  ON public.comments FOR INSERT
  WITH CHECK (auth.role() = 'authenticated' AND auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own comments" ON public.comments;
CREATE POLICY "Users can delete their own comments"
  ON public.comments FOR DELETE
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Likes are viewable by everyone" ON public.likes;
CREATE POLICY "Likes are viewable by everyone"
  ON public.likes FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Authenticated users can like" ON public.likes;
CREATE POLICY "Authenticated users can like"
  ON public.likes FOR INSERT
  WITH CHECK (auth.role() = 'authenticated' AND auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can remove likes" ON public.likes;
CREATE POLICY "Users can remove likes"
  ON public.likes FOR DELETE
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can see own notifications" ON public.notifications;
CREATE POLICY "Users can see own notifications"
  ON public.notifications FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own notifications" ON public.notifications;
CREATE POLICY "Users can update own notifications"
  ON public.notifications FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can see their saved events" ON public.saved_events;
CREATE POLICY "Users can see their saved events"
  ON public.saved_events FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can save events" ON public.saved_events;
CREATE POLICY "Users can save events"
  ON public.saved_events FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update saved events" ON public.saved_events;
CREATE POLICY "Users can update saved events"
  ON public.saved_events FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can unsave events" ON public.saved_events;
CREATE POLICY "Users can unsave events"
  ON public.saved_events FOR DELETE
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can see their saved posts" ON public.saved_posts;
CREATE POLICY "Users can see their saved posts"
  ON public.saved_posts FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can save posts" ON public.saved_posts;
CREATE POLICY "Users can save posts"
  ON public.saved_posts FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can unsave posts" ON public.saved_posts;
CREATE POLICY "Users can unsave posts"
  ON public.saved_posts FOR DELETE
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Post likes are viewable by everyone" ON public.post_likes;
CREATE POLICY "Post likes are viewable by everyone"
  ON public.post_likes FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Users can like posts" ON public.post_likes;
CREATE POLICY "Users can like posts"
  ON public.post_likes FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can unlike posts" ON public.post_likes;
CREATE POLICY "Users can unlike posts"
  ON public.post_likes FOR DELETE
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Post comments are viewable by everyone" ON public.post_comments;
CREATE POLICY "Post comments are viewable by everyone"
  ON public.post_comments FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Users can create post comments" ON public.post_comments;
CREATE POLICY "Users can create post comments"
  ON public.post_comments FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own post comments" ON public.post_comments;
CREATE POLICY "Users can delete own post comments"
  ON public.post_comments FOR DELETE
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Comment likes are viewable by everyone" ON public.comment_likes;
CREATE POLICY "Comment likes are viewable by everyone"
  ON public.comment_likes FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Users can like comments" ON public.comment_likes;
CREATE POLICY "Users can like comments"
  ON public.comment_likes FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can unlike comments" ON public.comment_likes;
CREATE POLICY "Users can unlike comments"
  ON public.comment_likes FOR DELETE
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Event likes are viewable by everyone" ON public.event_likes;
CREATE POLICY "Event likes are viewable by everyone"
  ON public.event_likes FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Users can like events" ON public.event_likes;
CREATE POLICY "Users can like events"
  ON public.event_likes FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can unlike events" ON public.event_likes;
CREATE POLICY "Users can unlike events"
  ON public.event_likes FOR DELETE
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Follows are viewable by everyone" ON public.follows;
CREATE POLICY "Follows are viewable by everyone"
  ON public.follows FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Users can insert their own follows" ON public.follows;
CREATE POLICY "Users can insert their own follows"
  ON public.follows FOR INSERT
  WITH CHECK (auth.uid() = follower_id);

DROP POLICY IF EXISTS "Users can delete their own follows" ON public.follows;
CREATE POLICY "Users can delete their own follows"
  ON public.follows FOR DELETE
  USING (auth.uid() = follower_id);

DROP POLICY IF EXISTS "User media is viewable by everyone" ON public.user_media;
CREATE POLICY "User media is viewable by everyone"
  ON public.user_media FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Users can upload media" ON public.user_media;
CREATE POLICY "Users can upload media"
  ON public.user_media FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update media" ON public.user_media;
CREATE POLICY "Users can update media"
  ON public.user_media FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete media" ON public.user_media;
CREATE POLICY "Users can delete media"
  ON public.user_media FOR DELETE
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can see their tickets" ON public.tickets;
CREATE POLICY "Users can see their tickets"
  ON public.tickets FOR SELECT
  USING (
    auth.uid() = user_id
    OR EXISTS (
      SELECT 1 FROM public.events e
      WHERE e.id = tickets.event_id
        AND e.organizer_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Users can insert transactions" ON public.transactions;
CREATE POLICY "Users can insert transactions"
  ON public.transactions FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view their own transactions" ON public.transactions;
CREATE POLICY "Users can view their own transactions"
  ON public.transactions FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Stream chat messages are viewable by everyone" ON public.stream_chat_messages;
CREATE POLICY "Stream chat messages are viewable by everyone"
  ON public.stream_chat_messages FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Authenticated users can send stream messages" ON public.stream_chat_messages;
CREATE POLICY "Authenticated users can send stream messages"
  ON public.stream_chat_messages FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view own conversations" ON public.conversations;
CREATE POLICY "Users can view own conversations"
  ON public.conversations FOR SELECT
  USING (auth.uid() = participant1_id OR auth.uid() = participant2_id);

DROP POLICY IF EXISTS "Users can create conversations" ON public.conversations;
CREATE POLICY "Users can create conversations"
  ON public.conversations FOR INSERT
  WITH CHECK (auth.uid() = participant1_id);

DROP POLICY IF EXISTS "Users can delete own conversations" ON public.conversations;
CREATE POLICY "Users can delete own conversations"
  ON public.conversations FOR DELETE
  USING (auth.uid() = participant1_id OR auth.uid() = participant2_id);

DROP POLICY IF EXISTS "Users can view messages in own conversations" ON public.messages;
CREATE POLICY "Users can view messages in own conversations"
  ON public.messages FOR SELECT
  USING (
    EXISTS (
      SELECT 1
      FROM public.conversations c
      WHERE c.id = messages.conversation_id
        AND (c.participant1_id = auth.uid() OR c.participant2_id = auth.uid())
    )
  );

DROP POLICY IF EXISTS "Users can insert messages in own conversations" ON public.messages;
CREATE POLICY "Users can insert messages in own conversations"
  ON public.messages FOR INSERT
  WITH CHECK (
    auth.uid() = sender_id
    AND EXISTS (
      SELECT 1
      FROM public.conversations c
      WHERE c.id = conversation_id
        AND (c.participant1_id = auth.uid() OR c.participant2_id = auth.uid())
    )
  );

DROP POLICY IF EXISTS "Users can update messages in own conversations" ON public.messages;
CREATE POLICY "Users can update messages in own conversations"
  ON public.messages FOR UPDATE
  USING (
    EXISTS (
      SELECT 1
      FROM public.conversations c
      WHERE c.id = messages.conversation_id
        AND (c.participant1_id = auth.uid() OR c.participant2_id = auth.uid())
    )
  );

DROP POLICY IF EXISTS "Users can delete messages in own conversations" ON public.messages;
CREATE POLICY "Users can delete messages in own conversations"
  ON public.messages FOR DELETE
  USING (
    EXISTS (
      SELECT 1
      FROM public.conversations c
      WHERE c.id = messages.conversation_id
        AND (c.participant1_id = auth.uid() OR c.participant2_id = auth.uid())
    )
  );

DROP POLICY IF EXISTS "Cloudflare streams are viewable by everyone" ON public.cloudflare_streams;
CREATE POLICY "Cloudflare streams are viewable by everyone"
  ON public.cloudflare_streams FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Users can manage their own Cloudflare streams" ON public.cloudflare_streams;
CREATE POLICY "Users can manage their own Cloudflare streams"
  ON public.cloudflare_streams FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view own roles" ON public.user_roles;
CREATE POLICY "Users can view own roles"
  ON public.user_roles FOR SELECT
  USING (auth.uid() = user_id OR public.has_role(auth.uid(), 'admin'));

DROP POLICY IF EXISTS "Admins can manage user roles" ON public.user_roles;
CREATE POLICY "Admins can manage user roles"
  ON public.user_roles FOR ALL
  USING (public.has_role(auth.uid(), 'admin'))
  WITH CHECK (public.has_role(auth.uid(), 'admin'));

DROP POLICY IF EXISTS "Admins can view audit logs" ON public.audit_logs;
CREATE POLICY "Admins can view audit logs"
  ON public.audit_logs FOR SELECT
  USING (public.has_role(auth.uid(), 'admin'));

DROP POLICY IF EXISTS "Admins can insert audit logs" ON public.audit_logs;
CREATE POLICY "Admins can insert audit logs"
  ON public.audit_logs FOR INSERT
  WITH CHECK (public.has_role(auth.uid(), 'admin'));

DROP POLICY IF EXISTS "Feature flags are viewable by everyone" ON public.feature_flags;
CREATE POLICY "Feature flags are viewable by everyone"
  ON public.feature_flags FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Admins can manage feature flags" ON public.feature_flags;
CREATE POLICY "Admins can manage feature flags"
  ON public.feature_flags FOR ALL
  USING (public.has_role(auth.uid(), 'admin'))
  WITH CHECK (public.has_role(auth.uid(), 'admin'));

DROP POLICY IF EXISTS "Users can create reports" ON public.reports;
CREATE POLICY "Users can create reports"
  ON public.reports FOR INSERT
  WITH CHECK (auth.uid() = reporter_id);

DROP POLICY IF EXISTS "Users can view own reports" ON public.reports;
CREATE POLICY "Users can view own reports"
  ON public.reports FOR SELECT
  USING (auth.uid() = reporter_id OR public.has_role(auth.uid(), 'admin') OR public.has_role(auth.uid(), 'moderator'));

DROP POLICY IF EXISTS "Moderators can update reports" ON public.reports;
CREATE POLICY "Moderators can update reports"
  ON public.reports FOR UPDATE
  USING (public.has_role(auth.uid(), 'admin') OR public.has_role(auth.uid(), 'moderator'))
  WITH CHECK (public.has_role(auth.uid(), 'admin') OR public.has_role(auth.uid(), 'moderator'));

-- ---------------------------------------------------------------------------
-- Storage buckets and policies
-- ---------------------------------------------------------------------------

INSERT INTO storage.buckets (id, name, public)
VALUES
  ('avatars', 'avatars', true),
  ('events', 'events', true),
  ('posts', 'posts', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Public Access" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can upload" ON storage.objects;
DROP POLICY IF EXISTS "Users can update own files" ON storage.objects;
DROP POLICY IF EXISTS "Users can delete own files" ON storage.objects;

DROP POLICY IF EXISTS "Avatar Public Access" ON storage.objects;
CREATE POLICY "Avatar Public Access"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'avatars');

DROP POLICY IF EXISTS "Avatar Auth Upload" ON storage.objects;
CREATE POLICY "Avatar Auth Upload"
  ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'avatars' AND auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Avatar Owner Update" ON storage.objects;
CREATE POLICY "Avatar Owner Update"
  ON storage.objects FOR UPDATE
  USING (bucket_id = 'avatars' AND auth.uid() = owner);

DROP POLICY IF EXISTS "Avatar Owner Delete" ON storage.objects;
CREATE POLICY "Avatar Owner Delete"
  ON storage.objects FOR DELETE
  USING (bucket_id = 'avatars' AND auth.uid() = owner);

DROP POLICY IF EXISTS "Event Public Access" ON storage.objects;
CREATE POLICY "Event Public Access"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'events');

DROP POLICY IF EXISTS "Event Auth Upload" ON storage.objects;
CREATE POLICY "Event Auth Upload"
  ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'events' AND auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Event Owner Update" ON storage.objects;
CREATE POLICY "Event Owner Update"
  ON storage.objects FOR UPDATE
  USING (bucket_id = 'events' AND auth.uid() = owner);

DROP POLICY IF EXISTS "Event Owner Delete" ON storage.objects;
CREATE POLICY "Event Owner Delete"
  ON storage.objects FOR DELETE
  USING (bucket_id = 'events' AND auth.uid() = owner);

DROP POLICY IF EXISTS "Post Public Access" ON storage.objects;
CREATE POLICY "Post Public Access"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'posts');

DROP POLICY IF EXISTS "Post Auth Upload" ON storage.objects;
CREATE POLICY "Post Auth Upload"
  ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'posts' AND auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Post Owner Update" ON storage.objects;
CREATE POLICY "Post Owner Update"
  ON storage.objects FOR UPDATE
  USING (bucket_id = 'posts' AND auth.uid() = owner);

DROP POLICY IF EXISTS "Post Owner Delete" ON storage.objects;
CREATE POLICY "Post Owner Delete"
  ON storage.objects FOR DELETE
  USING (bucket_id = 'posts' AND auth.uid() = owner);

-- ---------------------------------------------------------------------------
-- Grants
-- ---------------------------------------------------------------------------

GRANT EXECUTE ON FUNCTION public.become_organizer(TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.downgrade_to_personal_account() TO authenticated;
GRANT EXECUTE ON FUNCTION public.purchase_ticket(BIGINT, TEXT, TEXT, TEXT, TEXT, TEXT, UUID, TEXT, BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.purchase_ticket(BIGINT, TEXT, TEXT, TEXT, TEXT, TEXT, UUID, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.purchase_ticket(BIGINT, TEXT, TEXT, TEXT, TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.scan_ticket(TEXT, BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.delete_event_complete(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.increment_event_view(BIGINT) TO authenticated, anon;
GRANT EXECUTE ON FUNCTION public.increment_post_view(BIGINT) TO authenticated, anon;
GRANT EXECUTE ON FUNCTION public.increment_media_view(BIGINT) TO authenticated, anon;
GRANT EXECUTE ON FUNCTION public.get_organizer_stats(UUID) TO authenticated, anon;
GRANT EXECUTE ON FUNCTION public.get_event_analytics(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_role(UUID, public.app_role) TO authenticated;
