export const CREATOR_CATEGORIES = [
  'Art Gallery', 
  'Artist', 
  'Bar', 
  'Bar & Grill', 
  'Band', 
  'Blogger', 
  'Book Store', 
  'Brand',
  'Broadcasting & Media Production Company',
  'Business', 
  'Cafe', 
  'Charity', 
  'Church', 
  'Club', 
  'Coach', 
  'Comedy Club',
  'Community', 
  'Concert Venue', 
  'Conference', 
  'Content Creator', 
  'Corporate',
  'DJ', 
  'Dance Studio', 
  'Digital Creator', 
  'Education', 
  'Entrepreneur',
  'Event',
  'Entertainment',
  'Event Curator',
  'Event Organizer',
  'Event Planner', 
  'Exhibition', 
  'Fashion', 
  'Festival', 
  'Fitness Trainer',
  'Government', 
  'Gym', 
  'Health/Beauty', 
  'Hotel', 
  'Influencer', 
  'Library',
  'Lounge', 
  'Media', 
  'Mosque', 
  'Museum', 
  'Music Venue', 
  'Musician',
  'Networking Group', 
  'Nightclub', 
  'NGO',
  'Non-Profit', 
  'Organization', 
  'Park',
  'Party Planner', 
  'Performing Arts', 
  'Personal Blog', 
  'Photographer',
  'Podcast', 
  'Product/Service', 
  'Promoter', 
  'Public Figure', 
  'Radio Station',
  'Religious Organization', 
  'Resort', 
  'Restaurant', 
  'Retail', 
  'School',
  'Shopping', 
  'Social Club', 
  'Speaker', 
  'Sports Team', 
  'Startup',
  'Sports Event',
  'Student Organization', 
  'Synagogue', 
  'Tech Community', 
  'Theater',
  'TV Network',
  'University', 
  'Venue', 
  'Video Creator', 
  'Wedding Planner', 
  'Workshop',
  'Writer', 
  'Yoga Studio', 
  'Youth Organization'
].sort();
