export const eventsData = [
  {
    id: 9,
    title: 'Island Vibes - Live Performance Night',
    category: 'Entertainment',
    subcategory: 'Live Performances',
    image_url: 'https://i.ibb.co/6cfVDhDK/Harmonize-Shanga.jpg',
    date: '2025-06-15',
    time: '22:00',
    location: 'Shanga',
    city: 'zanzibar',
    price_range: 'TSh 22,000',
    attendees: 2345,
    description: 'Zanzibar\'s hotspot for electrifying live performances, themed nightlife parties, and unforgettable entertainment experiences where every night becomes a celebration of music, culture, and energy.',
    ticket_tiers: [
      {
        name: 'Normal',
        price: 'TSh 22,000',
        priceNumeric: 22000,
        available: 200,
        features: ['General admission', 'Dance floor access', 'Standard bar'],
      },
      {
        name: 'VIP',
        price: 'TSh 45,000',
        priceNumeric: 45000,
        available: 75,
        features: ['VIP lounge area', 'Priority entry', 'Reserved seating', 'Complimentary drink', 'Meet & greet opportunity'],
      },
      {
        name: 'VVIP',
        price: 'TSh 85,000',
        priceNumeric: 85000,
        available: 30,
        features: ['Private beachfront booth', 'Premium bottle service', 'Personal host', 'Backstage access', 'Exclusive photo opportunity', 'Complimentary food & drinks'],
      },
    ],
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: 'TSh 12,000',
      isLive: true,
      liveViewers: 1567,
      replayAvailable: true,
      features: ['Multi-camera angles', 'Live performances', 'HD streaming', 'Live chat'],
    },
    event_highlights: [
      {
        video: 'https://www.youtube.com/embed/2KPMETbdbOU',
        caption: 'DJ Amani - Live Performance Highlight',
        type: 'performer',
        mediaType: 'video',
      },
      {
        image: 'https://images.unsplash.com/photo-1593459866242-426f7768f3dc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhcnRpc3QlMjBtdXNpY2lhbiUyMHBvcnRyYWl0fGVufDF8fHx8MTc2NTg4MjA3OHww&ixlib=rb-4.1.0&q=80&w=1080',
        caption: 'Special Guest: Msanii Wa Taarabu',
        type: 'special_guest',
        mediaType: 'image',
      },
      {
        video: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        caption: 'Crowd Energy - Live Moment',
        type: 'preview',
        mediaType: 'video',
      },
      {
        image: 'https://images.unsplash.com/photo-1764212694488-8f852629a880?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxldmVudCUyMHZlbnVlJTIwbmlnaHR8ZW58MXx8fHwxNzY1ODk1MTEwfDA&ixlib=rb-4.1.0&q=80&w=1080',
        caption: 'Shanga Venue - Island Paradise Setting',
        type: 'venue',
        mediaType: 'image',
      },
    ],
  },
  {
    id: 2,
    title: 'Electric Nights - Themed Party',
    category: 'Entertainment',
    subcategory: 'Nightlife',
    image_url: 'https://i.ibb.co/n8Rk2bBZ/Tyler-ICU.jpg',
    date: '2025-06-20',
    time: '22:00',
    location: 'Elements Nightclub',
    city: 'dar',
    price_range: 'TSh 25,000',
    attendees: 1523,
    description: 'Dar es Salaam\'s iconic nightclub delivers premier nightlife party experience with themed events and exceptional live performances.',
    ticket_tiers: [
      {
        name: 'Normal',
        price: 'TSh 25,000',
        priceNumeric: 25000,
        available: 150,
        features: ['General admission', 'Access to main floor', 'Standard bar service'],
      },
      {
        name: 'VIP',
        price: 'TSh 50,000',
        priceNumeric: 50000,
        available: 50,
        features: ['VIP lounge access', 'Priority entry', 'Complimentary welcome drink', 'Reserved seating area', 'Express bar service'],
      },
      {
        name: 'VVIP',
        price: 'TSh 100,000',
        priceNumeric: 100000,
        available: 20,
        features: ['Private VIP booth', 'Premium bottle service', 'Dedicated server', 'Backstage meet & greet', 'Exclusive access areas', 'Complimentary champagne'],
      },
    ],
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: 'TSh 12,000',
      isLive: true,
      liveViewers: 1247,
      replayAvailable: true,
      features: ['Live DJ sets', 'Multi-angle cameras', 'HD streaming', 'Live chat'],
    },
    event_highlights: [
      {
        video: 'https://www.youtube.com/embed/2KPMETbdbOU',
        caption: 'Electric Vibes - DJ Set Highlight',
        type: 'preview',
        mediaType: 'video',
      },
      {
        image: 'https://i.ibb.co/GQLDDwSp/616124510-3065207627023296-5502080365092613571-n.jpg',
        caption: 'Live Performance Act',
        type: 'performer',
        mediaType: 'image',
      },
      {
        image: 'https://images.unsplash.com/photo-1764212694488-8f852629a880?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxldmVudCUyMHZlbnVlJTIwbmlnaHR8ZW58MXx8fHwxNzY1ODk1MTEwfDA&ixlib=rb-4.1.0&q=80&w=1080',
        caption: 'Elements Nightclub - VIP Experience',
        type: 'venue',
        mediaType: 'image',
      },
    ],
  },
  {
    id: 5,
    title: 'Swahili Fashion Week Showcase',
    category: 'Culture',
    subcategory: 'Fashion & Arts',
    image_url: 'https://i.ibb.co/jZ1XS3zk/Vintage-space.jpg',
    date: '2025-06-12',
    time: '19:00',
    location: 'Vintage Space',
    city: 'dar',
    price_range: 'TSh 35,000',
    attendees: 645,
    description: 'Dar es Salaam\'s premier fashion event showcasing cutting-edge fashion, style, and creativity from Tanzania\'s most talented designers and fashion innovators.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: 'TSh 15,000',
      isLive: false,
      liveViewers: 0,
      replayAvailable: true,
      features: ['Runway multi-cam', 'HD streaming', 'Designer interviews', 'Live chat'],
    },
  },
  {
    id: 1,
    title: 'Jungle Rhythms Night 2025',
    category: 'Entertainment',
    subcategory: 'Live Performances',
    image_url: 'https://images.unsplash.com/photo-1756978303719-57095d8bd250?w=800&h=600&fit=crop',
    date: '2025-06-14',
    time: '20:00',
    location: 'Summer Jungle',
    city: 'zanzibar',
    price_range: 'TSh 20,000',
    attendees: 2847,
    description: 'Experience the wild side of island nightlife with Afro music, house music, and outdoor festival vibes in Zanzibar\'s legendary bush club.',
    streaming: {
      available: true,
      quality: '4K',
      virtualPrice: 'TSh 10,000',
      isLive: false,
      liveViewers: 0,
      replayAvailable: true,
      features: ['Multi-camera angles', 'Live chat', 'HD & 4K quality', 'DVR replay'],
    },
  },
  {
    id: 3,
    title: 'Zanzibar Beach Festival',
    category: 'Culture',
    subcategory: 'Festivals',
    image_url: 'https://images.unsplash.com/photo-1707296450219-2d9cc08bdef0?w=800&h=600&fit=crop',
    date: '2025-07-07',
    time: '16:00',
    location: 'Nungwi Beach',
    city: 'zanzibar',
    price_range: 'Free',
    attendees: 3421,
    description: 'Experience traditional Swahili culture, live music, and authentic coastal cuisine at sunset.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: 'Free',
      isLive: false,
      liveViewers: 0,
      replayAvailable: false,
      features: ['Live broadcast', 'HD quality', 'Real-time reactions'],
    },
  },
  {
    id: 4,
    title: 'Masquerade Night - Themed Party',
    category: 'Entertainment',
    subcategory: 'Nightlife',
    image_url: 'https://images.unsplash.com/photo-1675674683873-1232862e3c64?w=800&h=600&fit=crop',
    date: '2025-06-28',
    time: '22:00',
    location: 'WE OUTCHEA',
    city: 'dar',
    price_range: 'TSh 15,000',
    attendees: 1876,
    description: 'Dar es Salaam\'s premier nightlife destination presents an unforgettable masquerade themed party with vibrant atmospheres where music, culture, and entertainment come alive.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: 'TSh 8,000',
      isLive: false,
      liveViewers: 0,
      replayAvailable: true,
      features: ['Multi-camera angles', 'Live DJ sets', 'HD streaming', 'Live chat'],
    },
  },
  {
    id: 6,
    title: 'Afro Beats Festival 2025',
    category: 'Entertainment',
    subcategory: 'Music Festival',
    image_url: 'https://images.unsplash.com/photo-1764050359179-517599dab87b?w=800&h=600&fit=crop',
    date: '2025-06-18',
    time: '18:00',
    location: 'The Park',
    city: 'dar',
    price_range: 'TSh 15,000',
    attendees: 8934,
    description: 'Premier music festival organizer and nightlife experience curator presents an unforgettable celebration of Afro beats, themed parties, and the best of Tanzanian entertainment culture.',
    streaming: {
      available: true,
      quality: '4K',
      virtualPrice: 'TSh 8,000',
      isLive: true,
      liveViewers: 5834,
      replayAvailable: true,
      features: ['4K Ultra HD', 'Multiple stage cameras', 'Live performances', 'Live chat'],
    },
  },
  {
    id: 7,
    title: 'Afro House Beach Party',
    category: 'Entertainment',
    subcategory: 'Beach Party',
    image_url: 'https://images.unsplash.com/photo-1764510377576-d2dd1cbd121d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxESiUyMG5pZ2h0Y2x1YiUyMHBlcmZvcm1hbmNlJTIwbGlnaHRzfGVufDF8fHx8MTc2NTgwOTYzOXww&ixlib=rb-4.1.0&q=80&w=1080',
    date: '2025-06-21',
    time: '21:00',
    location: 'Jambo Beach Party',
    city: 'zanzibar',
    price_range: 'TSh 20,000',
    attendees: 1234,
    description: 'Zanzibar\'s premier beach club featuring nightlife party experiences with Afro music, house music, and beachside entertainment - the ultimate destination for music lovers and party enthusiasts.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: 'TSh 10,000',
      isLive: false,
      liveViewers: 0,
      replayAvailable: true,
      features: ['Beach multi-cam', 'Live DJ sets', 'HD streaming', 'Live chat'],
    },
  },
  {
    id: 8,
    title: 'Beach Nightlife Experience',
    category: 'Entertainment',
    subcategory: 'Nightlife',
    image_url: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=600&fit=crop',
    date: '2025-06-23',
    time: '21:00',
    location: 'Kidimbwi Club',
    city: 'dar',
    price_range: 'TSh 18,000',
    attendees: 567,
    description: 'Beachfront party destination delivering exceptional nightlife party experiences where oceanfront dining meets high-energy entertainment in a tropical paradise setting.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: 'TSh 10,000',
      isLive: true,
      liveViewers: 345,
      replayAvailable: true,
      features: ['Beach multi-cam', 'Live DJ sets', 'HD streaming', 'Live chat'],
    },
  },
  {
    id: 10,
    title: 'Sunrise Beach Party',
    category: 'Entertainment',
    subcategory: 'Beach Party',
    image_url: 'https://images.unsplash.com/photo-1588286840104-8957b019727f?w=800&h=600&fit=crop',
    date: '2025-06-19',
    time: '05:30',
    location: 'Wavuvi Camp',
    city: 'dar',
    price_range: 'TSh 12,000',
    attendees: 234,
    description: 'Iconic bar and restaurant on Dar es Salaam\'s coastline, renowned for legendary sunrise parties and electrifying live performances where the night transforms into unforgettable nightlife experiences by the ocean.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: 'TSh 6,000',
      isLive: false,
      liveViewers: 0,
      replayAvailable: true,
      features: ['Sunrise multi-cam', 'Live performances', 'HD streaming', 'Live chat'],
    },
  },
  {
    id: 11,
    title: 'Broadway Night: Hamilton Live',
    category: 'Entertainment',
    subcategory: 'Live Performances',
    image_url: 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=800&h=600&fit=crop',
    date: '2025-06-27',
    time: '19:30',
    location: 'Richard Rodgers Theatre',
    city: 'newyork',
    price_range: '$180 - $450',
    attendees: 1456,
    description: 'Experience the award-winning musical Hamilton live on Broadway. Don\'t miss this spectacular performance!',
    streaming: {
      available: true,
      quality: '4K',
      virtualPrice: '$45',
      isLive: true,
      liveViewers: 3421,
      replayAvailable: true,
      features: ['4K streaming', 'Behind the scenes', 'Multi-angle views', 'Live subtitles'],
    },
  },
  {
    id: 12,
    title: 'Rooftop Cocktail Experience',
    category: 'Entertainment',
    subcategory: 'Nightlife (Bars/Lounges)',
    image_url: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800&h=600&fit=crop',
    date: '2025-07-02',
    time: '18:00',
    location: 'The Rooftop at Ponce City Market',
    city: 'atlanta',
    price_range: '$30',
    attendees: 567,
    description: 'Sip craft cocktails while enjoying stunning city views and live acoustic music.',
    streaming: {
      available: false,
      quality: 'SD',
    },
  },
  {
    id: 13,
    title: '80s Neon Party Night',
    category: 'Entertainment',
    subcategory: 'Themed Parties',
    image_url: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&h=600&fit=crop',
    date: '2025-07-05',
    time: '21:00',
    location: 'Club Retro',
    city: 'newyork',
    price_range: '$25',
    attendees: 892,
    description: 'Time travel to the 80s! Dress in your best neon outfit and dance to classic hits all night long.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: '$10',
      isLive: false,
      liveViewers: 0,
      replayAvailable: false,
      features: ['HD streaming', 'Live chat', 'Playlist access'],
    },
  },
  {
    id: 14,
    title: 'Photography Masterclass',
    category: 'Education',
    subcategory: 'Workshops',
    image_url: 'https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=800&h=600&fit=crop',
    date: '2025-06-21',
    time: '10:00',
    location: 'Dar es Salaam Art Center',
    city: 'dar',
    price_range: 'TSh 50,000',
    attendees: 145,
    description: 'Learn professional photography techniques from award-winning photographers. Hands-on training included.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: 'TSh 25,000',
      isLive: false,
      liveViewers: 0,
      replayAvailable: true,
      features: ['HD recording', 'Resource materials', 'Certificate', 'Q&A archive'],
    },
  },
  {
    id: 15,
    title: 'Leadership Excellence Seminar',
    category: 'Education',
    subcategory: 'Seminars',
    image_url: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800&h=600&fit=crop',
    date: '2025-06-24',
    time: '09:00',
    location: 'Hyatt Regency',
    city: 'atlanta',
    price_range: '$85',
    attendees: 456,
    description: 'Develop your leadership skills with insights from Fortune 500 executives and business coaches.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: '$45',
      isLive: true,
      liveViewers: 678,
      replayAvailable: true,
      features: ['HD streaming', 'Live Q&A', 'Digital workbook', 'Networking lobby'],
    },
  },
  {
    id: 16,
    title: 'AI & Machine Learning Webinar',
    category: 'Education',
    subcategory: 'Webinars',
    image_url: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=600&fit=crop',
    date: '2025-06-26',
    time: '15:00',
    location: 'Online Event',
    city: 'newyork',
    price_range: 'Free',
    attendees: 3421,
    description: 'Explore the future of AI and machine learning with leading experts from top tech companies.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: 'Free',
      isLive: true,
      liveViewers: 2845,
      replayAvailable: true,
      features: ['HD quality', 'Live chat', 'Slides download', 'Certificate'],
    },
  },
  {
    id: 17,
    title: 'Sauti za Busara Music Festival',
    category: 'Culture',
    subcategory: 'Festivals',
    image_url: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&h=600&fit=crop',
    date: '2025-07-11',
    time: '18:00',
    location: 'Old Fort Amphitheatre',
    city: 'zanzibar',
    price_range: 'TSh 30,000',
    attendees: 4567,
    description: 'Africa\'s premier celebration of music and culture featuring artists from across the continent.',
    streaming: {
      available: true,
      quality: '4K',
      virtualPrice: 'TSh 10,000',
      isLive: true,
      liveViewers: 6234,
      replayAvailable: true,
      features: ['4K streaming', 'Multi-stage coverage', 'Artist interviews', 'Live chat'],
    },
  },
  {
    id: 18,
    title: 'Street Art Walking Tour',
    category: 'Culture',
    subcategory: 'Arts',
    image_url: 'https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?w=800&h=600&fit=crop',
    date: '2025-06-29',
    time: '14:00',
    location: 'Krog Street Tunnel',
    city: 'atlanta',
    price_range: '$15',
    attendees: 234,
    description: 'Discover Atlanta\'s vibrant street art scene with local artists as your guides.',
    streaming: {
      available: false,
      quality: 'SD',
    },
  },
  {
    id: 19,
    title: 'Taste of Tanzania',
    category: 'Culture',
    subcategory: 'Food & Drink',
    image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&h=600&fit=crop',
    date: '2025-07-12',
    time: '11:00',
    location: 'Mlimani City',
    city: 'dar',
    price_range: 'TSh 15,000',
    attendees: 2145,
    description: 'Sample authentic Tanzanian dishes, watch cooking demonstrations, and learn about local culinary traditions.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: 'TSh 5,000',
      isLive: false,
      liveViewers: 0,
      replayAvailable: true,
      features: ['HD recording', 'Recipe cards', 'Chef interviews'],
    },
  },
  {
    id: 20,
    title: 'Swahili Heritage Day',
    category: 'Culture',
    subcategory: 'Local Traditions',
    image_url: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=600&fit=crop',
    date: '2025-07-03',
    time: '10:00',
    location: 'Stone Town Cultural Center',
    city: 'zanzibar',
    price_range: 'Free',
    attendees: 1876,
    description: 'Celebrate Swahili culture with traditional dances, crafts, storytelling, and historical exhibitions.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: 'Free',
      isLive: true,
      liveViewers: 1234,
      replayAvailable: true,
      features: ['HD streaming', 'Cultural commentary', 'Live chat'],
    },
  },
  {
    id: 21,
    title: 'New York Fashion Week Preview',
    category: 'Culture',
    subcategory: 'Fashion Events',
    image_url: 'https://images.unsplash.com/photo-1558769132-cb1aea1f5097?w=800&h=600&fit=crop',
    date: '2025-07-09',
    time: '19:00',
    location: 'Spring Studios',
    city: 'newyork',
    price_range: '$250',
    attendees: 876,
    description: 'Get an exclusive preview of next season\'s hottest fashion trends from emerging designers.',
    streaming: {
      available: true,
      quality: '4K',
      virtualPrice: '$75',
      isLive: true,
      liveViewers: 4562,
      replayAvailable: true,
      features: ['4K runway coverage', 'Designer interviews', 'Multi-angle views', 'Fashion commentary'],
    },
  },
  {
    id: 22,
    title: 'Interfaith Prayer Gathering',
    category: 'Religion',
    subcategory: 'Religious Gatherings',
    image_url: 'https://images.unsplash.com/photo-1507692049790-de58290a4334?w=800&h=600&fit=crop',
    date: '2025-06-20',
    time: '18:00',
    location: 'Unity Center',
    city: 'dar',
    price_range: 'Free',
    attendees: 1234,
    description: 'Join people of all faiths for an evening of prayer, reflection, and unity in our diverse community.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: 'Free',
      isLive: true,
      liveViewers: 876,
      replayAvailable: true,
      features: ['HD streaming', 'Multi-language', 'Live prayers', 'Chat moderation'],
    },
  },
  {
    id: 23,
    title: 'Meditation & Mindfulness Retreat',
    category: 'Religion',
    subcategory: 'Spiritual Events',
    image_url: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&h=600&fit=crop',
    date: '2025-06-28',
    time: '08:00',
    location: 'Serenity Gardens',
    city: 'atlanta',
    price_range: '$65',
    attendees: 456,
    description: 'A day of guided meditation, mindfulness practices, and spiritual connection in peaceful natural surroundings.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: '$35',
      isLive: false,
      liveViewers: 0,
      replayAvailable: true,
      features: ['HD recording', 'Guided meditations', 'Resource materials', 'Follow-along sessions'],
    },
  },
  {
    id: 24,
    title: 'Startup Pitch Competition',
    category: 'Business & Tech',
    subcategory: 'Startup Events',
    image_url: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800&h=600&fit=crop',
    date: '2025-06-30',
    time: '17:00',
    location: 'TechHub Dar',
    city: 'dar',
    price_range: 'TSh 10,000',
    attendees: 567,
    description: 'Watch innovative startups pitch their ideas to investors. $50,000 prize for the winning team!',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: 'TSh 5,000',
      isLive: true,
      liveViewers: 892,
      replayAvailable: true,
      features: ['HD quality', 'Live voting', 'Investor Q&A', 'Pitch deck downloads'],
    },
  },
  {
    id: 25,
    title: 'Women in Tech Networking',
    category: 'Business & Tech',
    subcategory: 'Networking',
    image_url: 'https://images.unsplash.com/photo-1591115765373-5207764f72e7?w=800&h=600&fit=crop',
    date: '2025-07-03',
    time: '18:00',
    location: 'Microsoft Innovation Center',
    city: 'newyork',
    price_range: '$25',
    attendees: 678,
    description: 'Connect with inspiring women in technology. Featuring panel discussions, mentorship, and networking opportunities.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: '$15',
      isLive: true,
      liveViewers: 1234,
      replayAvailable: true,
      features: ['HD streaming', 'Virtual networking rooms', 'Live chat', 'Panel Q&A'],
    },
  },
  {
    id: 26,
    title: 'Blockchain & Web3 Summit',
    category: 'Business & Tech',
    subcategory: 'Tech Talks',
    image_url: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&h=600&fit=crop',
    date: '2025-07-08',
    time: '13:00',
    location: 'Avalon Hotel',
    city: 'atlanta',
    price_range: '$95',
    attendees: 1234,
    description: 'Explore the future of blockchain technology, cryptocurrencies, and Web3 with industry pioneers.',
    streaming: {
      available: true,
      quality: '4K',
      virtualPrice: '$50',
      isLive: true,
      liveViewers: 2345,
      replayAvailable: true,
      features: ['4K streaming', 'Speaker slides', 'Live Q&A', 'Networking chat'],
    },
  },
  {
    id: 27,
    title: 'CrossFit Competition',
    category: 'Sports & Fitness',
    subcategory: 'Competitions',
    image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&h=600&fit=crop',
    date: '2025-07-05',
    time: '08:00',
    location: 'Titan Fitness Arena',
    city: 'atlanta',
    price_range: '$15',
    attendees: 789,
    description: 'Watch elite athletes compete in intense CrossFit challenges. Free fitness expo and vendor village.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: '$10',
      isLive: true,
      liveViewers: 1567,
      replayAvailable: true,
      features: ['HD streaming', 'Live leaderboard', 'Athlete interviews', 'Multi-camera angles'],
    },
  },
  {
    id: 28,
    title: 'Sunrise Beach Bootcamp',
    category: 'Sports & Fitness',
    subcategory: 'Fitness Classes',
    image_url: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&h=600&fit=crop',
    date: '2025-06-24',
    time: '06:00',
    location: 'Msasani Beach',
    city: 'dar',
    price_range: 'TSh 5,000',
    attendees: 123,
    description: 'Start your day with an energizing beach workout. All fitness levels welcome!',
    streaming: {
      available: false,
      quality: 'SD',
    },
  },
  {
    id: 29,
    title: 'NYC Marathon 2025',
    category: 'Sports & Fitness',
    subcategory: 'Sports Events',
    image_url: 'https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?w=800&h=600&fit=crop',
    date: '2025-07-13',
    time: '07:00',
    location: 'Central Park Start Line',
    city: 'newyork',
    price_range: '$150',
    attendees: 15678,
    description: 'Run through the five boroughs of New York City in one of the world\'s most iconic marathons.',
    streaming: {
      available: true,
      quality: '4K',
      virtualPrice: 'Free',
      isLive: true,
      liveViewers: 23456,
      replayAvailable: true,
      features: ['4K coverage', 'Multiple checkpoints', 'Runner tracking', 'Highlights'],
    },
  },
  {
    id: 30,
    title: 'Zanzibar International Film Festival',
    category: 'Culture',
    subcategory: 'Festivals',
    image_url: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&h=600&fit=crop',
    date: '2025-07-16',
    time: '17:00',
    location: 'Old Fort Amphitheatre',
    city: 'zanzibar',
    price_range: 'TSh 25,000',
    attendees: 2567,
    description: 'Celebrating African cinema with screenings, Q&As with filmmakers, and cultural performances.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: 'TSh 10,000',
      isLive: true,
      liveViewers: 3456,
      replayAvailable: true,
      features: ['HD streaming', 'Director commentary', 'Festival coverage', 'Behind the scenes'],
    },
  },
  {
    id: 31,
    title: 'Underground House Party',
    category: 'Entertainment',
    subcategory: 'Club Nights',
    image_url: 'https://images.unsplash.com/photo-1574391884720-bbc3740c59d1?w=800&h=600&fit=crop',
    date: '2025-07-18',
    time: '23:00',
    location: 'The Warehouse TZ',
    city: 'dar',
    price_range: 'TSh 25,000',
    attendees: 678,
    description: 'Deep house and techno beats in Dar\'s most exclusive underground venue. Featuring local and international DJs.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: 'TSh 8,000',
      isLive: true,
      liveViewers: 892,
      replayAvailable: false,
      features: ['HD streaming', 'Live DJ sets', 'Chat with fans'],
    },
  },
  {
    id: 32,
    title: 'Masquerade Ball NYC',
    category: 'Entertainment',
    subcategory: 'Themed Parties',
    image_url: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&h=600&fit=crop',
    date: '2025-07-19',
    time: '20:00',
    location: 'The Plaza Hotel',
    city: 'newyork',
    price_range: '$85 - $150',
    attendees: 456,
    description: 'An elegant masquerade ball with live orchestra, champagne, and mysterious encounters in a glamorous setting.',
    streaming: {
      available: false,
      quality: 'SD',
    },
  },
  {
    id: 33,
    title: 'Jazz & Wine Night',
    category: 'Entertainment',
    subcategory: 'Nightlife (Bars/Lounges)',
    image_url: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=800&h=600&fit=crop',
    date: '2025-06-26',
    time: '19:00',
    location: 'Slipway Lounge',
    city: 'dar',
    price_range: 'TSh 35,000',
    attendees: 234,
    description: 'Sophisticated evening of smooth jazz with premium wine selection and ocean views at Dar\'s finest lounge.',
    streaming: {
      available: false,
      quality: 'SD',
    },
  },
  {
    id: 34,
    title: 'Tropical Beach Party',
    category: 'Entertainment',
    subcategory: 'Themed Parties',
    image_url: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&h=600&fit=crop',
    date: '2025-06-28',
    time: '15:00',
    location: 'Kendwa Beach',
    city: 'zanzibar',
    price_range: 'TSh 20,000',
    attendees: 1234,
    description: 'Beach paradise vibes with tropical drinks, fire dancers, and DJ sets under the palm trees until sunset.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: 'TSh 7,000',
      isLive: false,
      liveViewers: 0,
      replayAvailable: true,
      features: ['HD streaming', 'Beach party vibes', 'Sunset coverage'],
    },
  },
  {
    id: 35,
    title: 'Live Jazz at Blue Note',
    category: 'Entertainment',
    subcategory: 'Live Performances',
    image_url: 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800&h=600&fit=crop',
    date: '2025-07-09',
    time: '20:00',
    location: 'Blue Note Jazz Club',
    city: 'newyork',
    price_range: '$45 - $75',
    attendees: 567,
    description: 'World-class jazz musicians perform at NYC\'s legendary Blue Note. Intimate setting with dinner service.',
    streaming: {
      available: true,
      quality: '4K',
      virtualPrice: '$25',
      isLive: true,
      liveViewers: 2134,
      replayAvailable: true,
      features: ['4K audio & video', 'Multi-camera angles', 'Live chat', 'Set list'],
    },
  },
  {
    id: 36,
    title: 'Indie Music Showcase',
    category: 'Entertainment',
    subcategory: 'Live Performances',
    image_url: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=800&h=600&fit=crop',
    date: '2025-07-11',
    time: '19:00',
    location: 'The Loft Atlanta',
    city: 'atlanta',
    price_range: '$20',
    attendees: 345,
    description: 'Discover Atlanta\'s best indie bands and emerging artists in an intimate venue. Supporting local music scene.',
    streaming: {
      available: false,
      quality: 'SD',
    },
  },
  {
    id: 37,
    title: 'Sunset Cocktails & DJ',
    category: 'Entertainment',
    subcategory: 'Nightlife (Bars/Lounges)',
    image_url: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800&h=600&fit=crop',
    date: '2025-07-04',
    time: '17:00',
    location: 'Forodhani Gardens',
    city: 'zanzibar',
    price_range: 'TSh 15,000',
    attendees: 456,
    description: 'Sunset cocktails with live DJ at Stone Town\'s waterfront. Perfect blend of chill vibes and great music.',
    streaming: {
      available: false,
      quality: 'SD',
    },
  },
  {
    id: 38,
    title: 'Excel Mastery Workshop',
    category: 'Education',
    subcategory: 'Workshops',
    image_url: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=600&fit=crop',
    date: '2025-07-01',
    time: '09:00',
    location: 'Business Hub Dar',
    city: 'dar',
    price_range: 'TSh 40,000',
    attendees: 234,
    description: 'Master Excel from basics to advanced formulas, pivot tables, and data analysis. Certificate included.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: 'TSh 20,000',
      isLive: false,
      liveViewers: 0,
      replayAvailable: true,
      features: ['HD recording', 'Practice files', 'Certificate', 'Lifetime access'],
    },
  },
  {
    id: 39,
    title: 'Public Speaking Masterclass',
    category: 'Education',
    subcategory: 'Workshops',
    image_url: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800&h=600&fit=crop',
    date: '2025-07-12',
    time: '10:00',
    location: 'Carnegie Hall Studios',
    city: 'newyork',
    price_range: '$95',
    attendees: 189,
    description: 'Overcome stage fright and deliver powerful presentations. Learn from Broadway coaches and TED speakers.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: '$50',
      isLive: true,
      liveViewers: 567,
      replayAvailable: true,
      features: ['HD quality', 'Interactive exercises', 'Feedback sessions', 'Resources'],
    },
  },
  {
    id: 40,
    title: 'Mental Health in Workplace',
    category: 'Education',
    subcategory: 'Seminars',
    image_url: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800&h=600&fit=crop',
    date: '2025-07-16',
    time: '14:00',
    location: 'Coca-Cola HQ',
    city: 'atlanta',
    price_range: '$40',
    attendees: 345,
    description: 'Understanding mental health challenges in modern workplaces. Expert psychologists and HR professionals.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: '$25',
      isLive: true,
      liveViewers: 678,
      replayAvailable: true,
      features: ['HD streaming', 'Q&A session', 'Resource materials', 'Certificate'],
    },
  },
  {
    id: 41,
    title: 'Tourism & Hospitality Seminar',
    category: 'Education',
    subcategory: 'Seminars',
    image_url: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=800&h=600&fit=crop',
    date: '2025-07-14',
    time: '09:00',
    location: 'Zanzibar Serena Hotel',
    city: 'zanzibar',
    price_range: 'TSh 30,000',
    attendees: 267,
    description: 'Strategies for excellence in tourism and hospitality industry. Network with industry leaders in Zanzibar.',
    streaming: {
      available: false,
      quality: 'SD',
    },
  },
  {
    id: 42,
    title: 'Climate Change Solutions',
    category: 'Education',
    subcategory: 'Webinars',
    image_url: 'https://images.unsplash.com/photo-1569163139394-de4798aa62b6?w=800&h=600&fit=crop',
    date: '2025-07-17',
    time: '16:00',
    location: 'Online Event',
    city: 'dar',
    price_range: 'Free',
    attendees: 2345,
    description: 'Global experts discuss practical climate solutions for East Africa. Interactive Q&A with scientists.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: 'Free',
      isLive: true,
      liveViewers: 1890,
      replayAvailable: true,
      features: ['HD streaming', 'Live Q&A', 'Slides download', 'Certificate'],
    },
  },
  {
    id: 43,
    title: 'Cryptocurrency 101 Webinar',
    category: 'Education',
    subcategory: 'Webinars',
    image_url: 'https://images.unsplash.com/photo-1621761191319-c6fb62004040?w=800&h=600&fit=crop',
    date: '2025-07-15',
    time: '19:00',
    location: 'Online Event',
    city: 'atlanta',
    price_range: '$15',
    attendees: 1678,
    description: 'Learn the basics of cryptocurrency, blockchain, and digital investing from financial experts.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: '$15',
      isLive: true,
      liveViewers: 1456,
      replayAvailable: true,
      features: ['HD quality', 'Live chat', 'Resource pack', 'Recording access'],
    },
  },
  {
    id: 44,
    title: 'Karibu Music & Arts Festival',
    category: 'Culture',
    subcategory: 'Festivals',
    image_url: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&h=600&fit=crop',
    date: '2025-07-19',
    time: '14:00',
    location: 'Oyster Bay',
    city: 'dar',
    price_range: 'TSh 25,000',
    attendees: 3456,
    description: 'Celebrate East African culture with live music, traditional dance, art exhibitions, and local cuisine.',
    streaming: {
      available: true,
      quality: '4K',
      virtualPrice: 'TSh 8,000',
      isLive: true,
      liveViewers: 4567,
      replayAvailable: true,
      features: ['4K streaming', 'Multi-stage coverage', 'Cultural performances', 'Artist interviews'],
    },
  },
  {
    id: 45,
    title: 'Atlanta Food Truck Festival',
    category: 'Culture',
    subcategory: 'Festivals',
    image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&h=600&fit=crop',
    date: '2025-07-20',
    time: '11:00',
    location: 'Piedmont Park',
    city: 'atlanta',
    price_range: 'Free',
    attendees: 5678,
    description: 'Over 50 food trucks serving diverse cuisines. Live music, craft beer garden, and family activities.',
    streaming: {
      available: false,
      quality: 'SD',
    },
  },
  {
    id: 46,
    title: 'Graffiti & Street Art Workshop',
    category: 'Culture',
    subcategory: 'Arts',
    image_url: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800&h=600&fit=crop',
    date: '2025-06-28',
    time: '13:00',
    location: 'Brooklyn Art District',
    city: 'newyork',
    price_range: '$55',
    attendees: 167,
    description: 'Learn spray paint techniques from NYC street art legends. Create your own piece to take home.',
    streaming: {
      available: false,
      quality: 'SD',
    },
  },
  {
    id: 47,
    title: 'Traditional Tinga Tinga Painting',
    category: 'Culture',
    subcategory: 'Arts',
    image_url: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800&h=600&fit=crop',
    date: '2025-07-10',
    time: '10:00',
    location: 'Stone Town Art Gallery',
    city: 'zanzibar',
    price_range: 'TSh 40,000',
    attendees: 123,
    description: 'Learn the iconic Tinga Tinga art style from master Zanzibari artists. All materials included.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: 'TSh 20,000',
      isLive: false,
      liveViewers: 0,
      replayAvailable: true,
      features: ['HD recording', 'Art techniques', 'Material list', 'Follow-along'],
    },
  },
  {
    id: 48,
    title: 'Wine Tasting Experience',
    category: 'Culture',
    subcategory: 'Food & Drink',
    image_url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&h=600&fit=crop',
    date: '2025-07-18',
    time: '18:00',
    location: 'The Georgian Terrace',
    city: 'atlanta',
    price_range: '$75',
    attendees: 234,
    description: 'Premium wine tasting featuring international selections paired with gourmet appetizers and sommelier guidance.',
    streaming: {
      available: false,
      quality: 'SD',
    },
  },
  {
    id: 49,
    title: 'Street Food Safari',
    category: 'Culture',
    subcategory: 'Food & Drink',
    image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&h=600&fit=crop',
    date: '2025-07-05',
    time: '17:00',
    location: 'Forodhani Night Market',
    city: 'zanzibar',
    price_range: 'TSh 10,000',
    attendees: 678,
    description: 'Guided tour of Zanzibar\'s famous night market. Taste authentic Swahili street food and seafood specialties.',
    streaming: {
      available: false,
      quality: 'SD',
    },
  },
  {
    id: 50,
    title: 'Makonde Carving Workshop',
    category: 'Culture',
    subcategory: 'Local Traditions',
    image_url: 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=800&h=600&fit=crop',
    date: '2025-07-13',
    time: '09:00',
    location: 'Mwenge Carvers Market',
    city: 'dar',
    price_range: 'TSh 35,000',
    attendees: 145,
    description: 'Learn traditional Makonde wood carving from master craftsmen. Hands-on workshop with tools provided.',
    streaming: {
      available: false,
      quality: 'SD',
    },
  },
  {
    id: 51,
    title: 'Native American Heritage Day',
    category: 'Culture',
    subcategory: 'Local Traditions',
    image_url: 'https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=800&h=600&fit=crop',
    date: '2025-07-12',
    time: '10:00',
    location: 'Central Park',
    city: 'newyork',
    price_range: 'Free',
    attendees: 2345,
    description: 'Celebrate Native American culture with traditional dances, storytelling, crafts, and authentic cuisine.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: 'Free',
      isLive: true,
      liveViewers: 3456,
      replayAvailable: true,
      features: ['HD streaming', 'Cultural performances', 'Educational content', 'Live chat'],
    },
  },
  {
    id: 52,
    title: 'Sustainable Fashion Show',
    category: 'Culture',
    subcategory: 'Fashion Events',
    image_url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&h=600&fit=crop',
    date: '2025-07-16',
    time: '19:00',
    location: 'Masaki Peninsula',
    city: 'dar',
    price_range: 'TSh 50,000',
    attendees: 456,
    description: 'Showcasing eco-friendly fashion from East African designers. Sustainable materials and ethical production.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: 'TSh 25,000',
      isLive: true,
      liveViewers: 1234,
      replayAvailable: true,
      features: ['HD runway', 'Designer interviews', 'Behind the scenes', 'Live commentary'],
    },
  },
  {
    id: 53,
    title: 'Bridal Fashion Expo',
    category: 'Culture',
    subcategory: 'Fashion Events',
    image_url: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&h=600&fit=crop',
    date: '2025-06-29',
    time: '12:00',
    location: 'Cobb Galleria Centre',
    city: 'atlanta',
    price_range: '$20',
    attendees: 1234,
    description: 'Discover the latest bridal trends. Meet designers, vendors, and get wedding planning inspiration.',
    streaming: {
      available: false,
      quality: 'SD',
    },
  },
  {
    id: 54,
    title: 'Friday Jummah Prayer',
    category: 'Religion',
    subcategory: 'Worship Services',
    image_url: 'https://images.unsplash.com/photo-1591604129939-f1efa4d9f7fa?w=800&h=600&fit=crop',
    date: '2025-06-27',
    time: '13:00',
    location: 'Islamic Center of Atlanta',
    city: 'atlanta',
    price_range: 'Free',
    attendees: 1567,
    description: 'Weekly Friday congregational prayer service with inspiring sermon and community gathering.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: 'Free',
      isLive: true,
      liveViewers: 2345,
      replayAvailable: true,
      features: ['HD streaming', 'Live sermon', 'Translations', 'Prayer times'],
    },
  },
  {
    id: 55,
    title: 'Church Praise & Worship Night',
    category: 'Religion',
    subcategory: 'Worship Services',
    image_url: 'https://images.unsplash.com/photo-1507692049790-de58290a4334?w=800&h=600&fit=crop',
    date: '2025-07-19',
    time: '18:00',
    location: 'Azania Front Lutheran Church',
    city: 'dar',
    price_range: 'Free',
    attendees: 1890,
    description: 'Powerful worship night with live gospel music, testimonies, and prayer. Everyone welcome.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: 'Free',
      isLive: true,
      liveViewers: 3456,
      replayAvailable: true,
      features: ['HD streaming', 'Live worship', 'Prayer requests', 'Song lyrics'],
    },
  },
  {
    id: 56,
    title: 'Interfaith Dialogue Forum',
    category: 'Religion',
    subcategory: 'Religious Gatherings',
    image_url: 'https://images.unsplash.com/photo-1529070538774-1843cb3265df?w=800&h=600&fit=crop',
    date: '2025-07-08',
    time: '16:00',
    location: 'Community Center NYC',
    city: 'newyork',
    price_range: 'Free',
    attendees: 567,
    description: 'Open dialogue between different faith communities. Promoting understanding, peace, and cooperation.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: 'Free',
      isLive: true,
      liveViewers: 890,
      replayAvailable: true,
      features: ['HD streaming', 'Multi-faith speakers', 'Q&A session', 'Live moderation'],
    },
  },
  {
    id: 57,
    title: 'Ramadan Iftar Gathering',
    category: 'Religion',
    subcategory: 'Religious Gatherings',
    image_url: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&h=600&fit=crop',
    date: '2025-06-30',
    time: '18:30',
    location: 'Old Fort Gardens',
    city: 'zanzibar',
    price_range: 'Free',
    attendees: 2345,
    description: 'Community iftar dinner breaking the fast together. Traditional food, prayer, and fellowship.',
    streaming: {
      available: false,
      quality: 'SD',
    },
  },
  {
    id: 58,
    title: 'Yoga & Meditation Retreat',
    category: 'Religion',
    subcategory: 'Spiritual Events',
    image_url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=600&fit=crop',
    date: '2025-07-06',
    time: '07:00',
    location: 'Stone Town Beach Resort',
    city: 'zanzibar',
    price_range: 'TSh 75,000',
    attendees: 234,
    description: 'Full day spiritual retreat combining yoga, meditation, and wellness practices by the Indian Ocean.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: 'TSh 35,000',
      isLive: false,
      liveViewers: 0,
      replayAvailable: true,
      features: ['HD recording', 'Guided sessions', 'Meditation tracks', 'Wellness guide'],
    },
  },
  {
    id: 59,
    title: 'Healing & Wellness Workshop',
    category: 'Religion',
    subcategory: 'Spiritual Events',
    image_url: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&h=600&fit=crop',
    date: '2025-06-21',
    time: '09:00',
    location: 'Dar Wellness Center',
    city: 'dar',
    price_range: 'TSh 55,000',
    attendees: 178,
    description: 'Holistic healing workshop covering energy work, crystal therapy, and spiritual wellness practices.',
    streaming: {
      available: false,
      quality: 'SD',
    },
  },
  {
    id: 60,
    title: 'Fintech Startup Accelerator',
    category: 'Business & Tech',
    subcategory: 'Startup Events',
    image_url: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800&h=600&fit=crop',
    date: '2025-07-10',
    time: '09:00',
    location: 'Times Square Office',
    city: 'newyork',
    price_range: '$200',
    attendees: 345,
    description: 'Intensive one-day program for fintech startups. Mentorship, pitching practice, and investor connections.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: '$100',
      isLive: true,
      liveViewers: 567,
      replayAvailable: true,
      features: ['HD quality', 'Startup pitches', 'Mentor sessions', 'Investor Q&A'],
    },
  },
  {
    id: 61,
    title: 'Zanzibar Entrepreneurs Meetup',
    category: 'Business & Tech',
    subcategory: 'Startup Events',
    image_url: 'https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=800&h=600&fit=crop',
    date: '2025-07-02',
    time: '17:00',
    location: 'Zanzibar Co-working Space',
    city: 'zanzibar',
    price_range: 'TSh 15,000',
    attendees: 234,
    description: 'Monthly gathering of island entrepreneurs. Share ideas, find collaborators, and grow your business.',
    streaming: {
      available: false,
      quality: 'SD',
    },
  },
  {
    id: 62,
    title: 'Professional Networking Mixer',
    category: 'Business & Tech',
    subcategory: 'Networking',
    image_url: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&h=600&fit=crop',
    date: '2025-07-15',
    time: '18:00',
    location: 'Hyatt Regency Dar',
    city: 'dar',
    price_range: 'TSh 20,000',
    attendees: 456,
    description: 'Connect with business professionals across industries. Complimentary drinks and appetizers included.',
    streaming: {
      available: false,
      quality: 'SD',
    },
  },
  {
    id: 63,
    title: 'Young Professionals Network',
    category: 'Business & Tech',
    subcategory: 'Networking',
    image_url: 'https://images.unsplash.com/photo-1528605105345-5344ea20e269?w=800&h=600&fit=crop',
    date: '2025-06-26',
    time: '18:30',
    location: 'The Battery Atlanta',
    city: 'atlanta',
    price_range: '$15',
    attendees: 678,
    description: 'Networking event for young professionals under 35. Build connections in a relaxed social atmosphere.',
    streaming: {
      available: false,
      quality: 'SD',
    },
  },
  {
    id: 64,
    title: 'East Africa Business Summit',
    category: 'Business & Tech',
    subcategory: 'Conferences',
    image_url: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=600&fit=crop',
    date: '2025-07-14',
    time: '08:00',
    location: 'Serena Hotel Zanzibar',
    city: 'zanzibar',
    price_range: 'TSh 150,000',
    attendees: 567,
    description: 'Regional business conference exploring trade, investment, and economic opportunities in East Africa.',
    streaming: {
      available: true,
      quality: '4K',
      virtualPrice: 'TSh 75,000',
      isLive: true,
      liveViewers: 1234,
      replayAvailable: true,
      features: ['4K streaming', 'All sessions', 'Networking lounge', 'Speaker slides'],
    },
  },
  {
    id: 65,
    title: 'Global Tech Conference 2025',
    category: 'Business & Tech',
    subcategory: 'Conferences',
    image_url: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=800&h=600&fit=crop',
    date: '2025-06-25',
    time: '09:00',
    location: 'Javits Center',
    city: 'newyork',
    price_range: '$350 - $500',
    attendees: 3456,
    description: 'The world\'s leading technology conference. Latest innovations, keynotes from tech giants, and networking.',
    streaming: {
      available: true,
      quality: '4K',
      virtualPrice: '$150',
      isLive: true,
      liveViewers: 8900,
      replayAvailable: true,
      features: ['4K streaming', 'Multi-track access', 'Virtual networking', 'On-demand replays'],
    },
  },
  {
    id: 66,
    title: 'Cybersecurity Best Practices',
    category: 'Business & Tech',
    subcategory: 'Tech Talks',
    image_url: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&h=600&fit=crop',
    date: '2025-07-11',
    time: '15:00',
    location: 'UDSM ICT Center',
    city: 'dar',
    price_range: 'TSh 25,000',
    attendees: 234,
    description: 'Learn essential cybersecurity practices for businesses. Protect your data and systems from threats.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: 'TSh 15,000',
      isLive: true,
      liveViewers: 456,
      replayAvailable: true,
      features: ['HD streaming', 'Security checklist', 'Q&A', 'Resources'],
    },
  },
  {
    id: 67,
    title: 'Future of AI Tech Talk',
    category: 'Business & Tech',
    subcategory: 'Tech Talks',
    image_url: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=600&fit=crop',
    date: '2025-06-30',
    time: '18:00',
    location: 'Georgia Tech',
    city: 'atlanta',
    price_range: '$30',
    attendees: 567,
    description: 'Experts discuss AI trends, ethical considerations, and real-world applications transforming industries.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: '$20',
      isLive: true,
      liveViewers: 890,
      replayAvailable: true,
      features: ['HD quality', 'Live discussion', 'Presentation slides', 'Chat Q&A'],
    },
  },
  {
    id: 68,
    title: 'Beach Volleyball Tournament',
    category: 'Sports & Fitness',
    subcategory: 'Competitions',
    image_url: 'https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=800&h=600&fit=crop',
    date: '2025-06-28',
    time: '08:00',
    location: 'Paje Beach',
    city: 'zanzibar',
    price_range: 'TSh 10,000',
    attendees: 456,
    description: 'Annual beach volleyball competition on Zanzibar\'s white sands. Open and pro divisions. Prizes awarded.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: 'TSh 5,000',
      isLive: true,
      liveViewers: 1234,
      replayAvailable: true,
      features: ['HD streaming', 'Match highlights', 'Live scores', 'Player interviews'],
    },
  },
  {
    id: 69,
    title: 'City Marathon Challenge',
    category: 'Sports & Fitness',
    subcategory: 'Competitions',
    image_url: 'https://images.unsplash.com/photo-1532444458054-01a7dd3e9fca?w=800&h=600&fit=crop',
    date: '2025-07-13',
    time: '06:00',
    location: 'Downtown Dar',
    city: 'dar',
    price_range: 'TSh 30,000',
    attendees: 2345,
    description: 'Run through Dar es Salaam\'s streets in this annual marathon. 5K, 10K, and full marathon options.',
    streaming: {
      available: true,
      quality: '4K',
      virtualPrice: 'Free',
      isLive: true,
      liveViewers: 5678,
      replayAvailable: true,
      features: ['4K coverage', 'Live tracking', 'Multiple cameras', 'Finish line feed'],
    },
  },
  {
    id: 70,
    title: 'HIIT Bootcamp Class',
    category: 'Sports & Fitness',
    subcategory: 'Fitness Classes',
    image_url: 'https://images.unsplash.com/photo-1601422407692-ec4eeec1d9b3?w=800&h=600&fit=crop',
    date: '2025-07-02',
    time: '06:00',
    location: 'Piedmont Park',
    city: 'atlanta',
    price_range: '$20',
    attendees: 156,
    description: 'High-intensity interval training in the park. All fitness levels welcome. Bring water and mat.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: '$10',
      isLive: true,
      liveViewers: 234,
      replayAvailable: false,
      features: ['HD streaming', 'Follow along', 'Live coaching'],
    },
  },
  {
    id: 71,
    title: 'Pilates & Stretching',
    category: 'Sports & Fitness',
    subcategory: 'Fitness Classes',
    image_url: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&h=600&fit=crop',
    date: '2025-07-05',
    time: '08:00',
    location: 'Brooklyn Bridge Park',
    city: 'newyork',
    price_range: '$25',
    attendees: 234,
    description: 'Outdoor pilates session with scenic views. Focus on core strength, flexibility, and mindful movement.',
    streaming: {
      available: false,
      quality: 'SD',
    },
  },
  {
    id: 72,
    title: 'NBA Finals Watch Party',
    category: 'Sports & Fitness',
    subcategory: 'Sports Events',
    image_url: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&h=600&fit=crop',
    date: '2025-06-19',
    time: '20:00',
    location: 'State Farm Arena',
    city: 'atlanta',
    price_range: '$35 - $75',
    attendees: 3456,
    description: 'Watch the NBA Finals on the big screen with thousands of fans. Food, drinks, and live entertainment.',
    streaming: {
      available: false,
      quality: 'SD',
    },
  },
  {
    id: 73,
    title: 'Football League Finals',
    category: 'Sports & Fitness',
    subcategory: 'Sports Events',
    image_url: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800&h=600&fit=crop',
    date: '2025-06-22',
    time: '16:00',
    location: 'Amaan Stadium',
    city: 'zanzibar',
    price_range: 'TSh 10,000 - 30,000',
    attendees: 5678,
    description: 'Championship match of Zanzibar Football League. Intense rivalry and passionate fans guaranteed.',
    streaming: {
      available: true,
      quality: '4K',
      virtualPrice: 'TSh 7,000',
      isLive: true,
      liveViewers: 12345,
      replayAvailable: true,
      features: ['4K streaming', 'Live commentary', 'Replays', 'Match stats'],
    },
  },
  {
    id: 74,
    title: 'Electro Night at Club 360',
    category: 'Entertainment',
    subcategory: 'Club Nights',
    image_url: 'https://images.unsplash.com/photo-1571266028243-d220c938a2f7?w=800&h=600&fit=crop',
    date: '2025-07-26',
    time: '22:00',
    location: 'Club 360 Rooftop',
    city: 'newyork',
    price_range: '$40 - $60',
    attendees: 789,
    description: 'Experience NYC nightlife at its finest. Top EDM DJs spinning all night with stunning city views.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: '$15',
      isLive: true,
      liveViewers: 1567,
      replayAvailable: true,
      features: ['HD streaming', 'Multiple DJ sets', 'VIP room access'],
    },
  },
  {
    id: 75,
    title: 'Afrobeat Festival',
    category: 'Entertainment',
    subcategory: 'Concerts',
    image_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=600&fit=crop',
    date: '2025-07-25',
    time: '19:00',
    location: 'Mlimani City Grounds',
    city: 'dar',
    price_range: 'TSh 30,000 - 50,000',
    attendees: 4567,
    description: 'The biggest Afrobeat concert in East Africa featuring Diamond Platnumz, Harmonize, and Zuchu live!',
    streaming: {
      available: true,
      quality: '4K',
      virtualPrice: 'TSh 15,000',
      isLive: true,
      liveViewers: 8900,
      replayAvailable: true,
      features: ['4K streaming', 'Backstage access', 'Artist meet & greet', 'Multi-camera'],
    },
  },
  {
    id: 76,
    title: 'Opera Under the Stars',
    category: 'Entertainment',
    subcategory: 'Concerts',
    image_url: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=800&h=600&fit=crop',
    date: '2025-07-19',
    time: '20:00',
    location: 'Stone Town Palace',
    city: 'zanzibar',
    price_range: 'TSh 45,000',
    attendees: 456,
    description: 'Classical opera performances in the historic palace gardens under the African night sky.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: 'TSh 20,000',
      isLive: true,
      liveViewers: 678,
      replayAvailable: true,
      features: ['HD audio & video', 'Subtitles', 'Program notes'],
    },
  },
  {
    id: 77,
    title: 'Country Music Night',
    category: 'Entertainment',
    subcategory: 'Concerts',
    image_url: 'https://images.unsplash.com/photo-1484876065684-b683cf17d276?w=800&h=600&fit=crop',
    date: '2025-07-24',
    time: '19:30',
    location: 'Chastain Park Amphitheatre',
    city: 'atlanta',
    price_range: '$55 - $125',
    attendees: 3456,
    description: 'Southern country music stars perform live. Bring your boots and cowboy hats for an authentic experience!',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: '$30',
      isLive: true,
      liveViewers: 2345,
      replayAvailable: true,
      features: ['HD streaming', 'Song lyrics', 'Artist interviews'],
    },
  },
  {
    id: 78,
    title: 'Glow Party Experience',
    category: 'Entertainment',
    subcategory: 'Themed Parties',
    image_url: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&h=600&fit=crop',
    date: '2025-07-18',
    time: '21:00',
    location: 'The Loft Midtown',
    city: 'atlanta',
    price_range: '$30',
    attendees: 567,
    description: 'Glow-in-the-dark party with neon body paint, UV lights, and electric beats. Free glow sticks included!',
    streaming: {
      available: false,
      quality: 'SD',
    },
  },
  {
    id: 79,
    title: 'Rooftop Sunset Sessions',
    category: 'Entertainment',
    subcategory: 'Nightlife (Bars/Lounges)',
    image_url: 'https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=800&h=600&fit=crop',
    date: '2025-07-20',
    time: '17:00',
    location: '230 Fifth Rooftop',
    city: 'newyork',
    price_range: '$35',
    attendees: 345,
    description: 'Sunset cocktails with panoramic Manhattan skyline views. Live DJ and craft cocktails.',
    streaming: {
      available: false,
      quality: 'SD',
    },
  },
  {
    id: 80,
    title: 'Digital Marketing Bootcamp',
    category: 'Education',
    subcategory: 'Workshops',
    image_url: 'https://images.unsplash.com/photo-1533750349088-cd871a92f312?w=800&h=600&fit=crop',
    date: '2025-07-21',
    time: '09:00',
    location: 'IFM Campus',
    city: 'dar',
    price_range: 'TSh 60,000',
    attendees: 189,
    description: 'Master digital marketing strategies: SEO, social media, email marketing, and analytics in one day.',
    streaming: {
      available: true,
      quality: 'HD',
      virtualPrice: 'TSh 30,000',
      isLive: true,
      liveViewers: 456,
      replayAvailable: true,
      features: ['HD streaming', 'Course materials', 'Certificate', 'Templates'],
    },
  },
];
