import { Globe } from 'lucide-react';

export type LocationOption = {
  id: string;
  name: string;
  flag?: string;
  icon?: any;
};

export const locations: LocationOption[] = [
  { id: 'all', name: 'All Cities', icon: Globe },
  { id: 'Dar es Salaam', name: 'Dar es Salaam', flag: '🇹🇿' },
  { id: 'Nairobi', name: 'Nairobi', flag: '🇰🇪' },
  { id: 'New York', name: 'New York', flag: '🇺🇸' },
  { id: 'London', name: 'London', flag: '🇬🇧' },
  { id: 'Toronto', name: 'Toronto', flag: '🇨🇦' },
  { id: 'Sydney', name: 'Sydney', flag: '🇦🇺' },
  { id: 'Berlin', name: 'Berlin', flag: '🇩🇪' },
  { id: 'Paris', name: 'Paris', flag: '🇫🇷' },
  { id: 'Rome', name: 'Rome', flag: '🇮🇹' },
  { id: 'Madrid', name: 'Madrid', flag: '🇪🇸' },
  { id: 'Amsterdam', name: 'Amsterdam', flag: '🇳🇱' },
  { id: 'Brussels', name: 'Brussels', flag: '🇧🇪' },
  { id: 'Zurich', name: 'Zurich', flag: '🇨🇭' },
  { id: 'Vienna', name: 'Vienna', flag: '🇦🇹' },
  { id: 'Stockholm', name: 'Stockholm', flag: '🇸🇪' },
  { id: 'Oslo', name: 'Oslo', flag: '🇳🇴' },
  { id: 'Copenhagen', name: 'Copenhagen', flag: '🇩🇰' },
  { id: 'Helsinki', name: 'Helsinki', flag: '🇫🇮' },
  { id: 'Warsaw', name: 'Warsaw', flag: '🇵🇱' },
  { id: 'Lisbon', name: 'Lisbon', flag: '🇵🇹' },
  { id: 'Athens', name: 'Athens', flag: '🇬🇷' },
  { id: 'Prague', name: 'Prague', flag: '🇨🇿' },
  { id: 'Dublin', name: 'Dublin', flag: '🇮🇪' },
  { id: 'Tokyo', name: 'Tokyo', flag: '🇯🇵' },
  { id: 'Seoul', name: 'Seoul', flag: '🇰🇷' },
  { id: 'Beijing', name: 'Beijing', flag: '🇨🇳' },
  { id: 'Mumbai', name: 'Mumbai', flag: '🇮🇳' },
  { id: 'Singapore', name: 'Singapore', flag: '🇸🇬' },
  { id: 'Bangkok', name: 'Bangkok', flag: '🇹🇭' },
  { id: 'Kuala Lumpur', name: 'Kuala Lumpur', flag: '🇲🇾' },
  { id: 'Jakarta', name: 'Jakarta', flag: '🇮🇩' },
  { id: 'Manila', name: 'Manila', flag: '🇵🇭' },
  { id: 'Hanoi', name: 'Hanoi', flag: '🇻🇳' },
  { id: 'Dubai', name: 'Dubai', flag: '🇦🇪' },
  { id: 'Riyadh', name: 'Riyadh', flag: '🇸🇦' },
  { id: 'Doha', name: 'Doha', flag: '🇶🇦' },
  { id: 'Jerusalem', name: 'Jerusalem', flag: '🇮🇱' },
  { id: 'Istanbul', name: 'Istanbul', flag: '🇹🇷' },
  { id: 'Rio de Janeiro', name: 'Rio de Janeiro', flag: '🇧🇷' },
  { id: 'Buenos Aires', name: 'Buenos Aires', flag: '🇦🇷' },
  { id: 'Mexico City', name: 'Mexico City', flag: '🇲🇽' },
  { id: 'Bogota', name: 'Bogota', flag: '🇨🇴' },
  { id: 'Santiago', name: 'Santiago', flag: '🇨🇱' },
  { id: 'Lima', name: 'Lima', flag: '🇵🇪' },
  { id: 'Cape Town', name: 'Cape Town', flag: '🇿🇦' },
  { id: 'Lagos', name: 'Lagos', flag: '🇳🇬' },
  { id: 'Cairo', name: 'Cairo', flag: '🇪🇬' },
  { id: 'Casablanca', name: 'Casablanca', flag: '🇲🇦' },
  { id: 'Accra', name: 'Accra', flag: '🇬🇭' },
  { id: 'Addis Ababa', name: 'Addis Ababa', flag: '🇪🇹' },
  { id: 'Kampala', name: 'Kampala', flag: '🇺🇬' },
  { id: 'Kigali', name: 'Kigali', flag: '🇷🇼' },
  { id: 'Lusaka', name: 'Lusaka', flag: '🇿🇲' },
  { id: 'Harare', name: 'Harare', flag: '🇿🇼' },
  { id: 'Gaborone', name: 'Gaborone', flag: '🇧🇼' },
  { id: 'Windhoek', name: 'Windhoek', flag: '🇳🇦' },
  { id: 'Maputo', name: 'Maputo', flag: '🇲🇿' },
  { id: 'Luanda', name: 'Luanda', flag: '🇦🇴' },
  { id: 'Dakar', name: 'Dakar', flag: '🇸🇳' },
  { id: 'Abidjan', name: 'Abidjan', flag: '🇨🇮' },
  { id: 'Yaounde', name: 'Yaounde', flag: '🇨🇲' },
  { id: 'Algiers', name: 'Algiers', flag: '🇩🇿' },
  { id: 'Tunis', name: 'Tunis', flag: '🇹🇳' },
  { id: 'Tripoli', name: 'Tripoli', flag: '🇱🇾' },
  { id: 'Khartoum', name: 'Khartoum', flag: '🇸🇩' },
  { id: 'Wellington', name: 'Wellington', flag: '🇳🇿' },
  { id: 'Moscow', name: 'Moscow', flag: '🇷🇺' },
  { id: 'Kyiv', name: 'Kyiv', flag: '🇺🇦' },
  { id: 'Budapest', name: 'Budapest', flag: '🇭🇺' },
  { id: 'Bucharest', name: 'Bucharest', flag: '🇷🇴' },
  { id: 'Sofia', name: 'Sofia', flag: '🇧🇬' },
  { id: 'Zagreb', name: 'Zagreb', flag: '🇭🇷' },
  { id: 'Belgrade', name: 'Belgrade', flag: '🇷🇸' },
  { id: 'Ljubljana', name: 'Ljubljana', flag: '🇸🇮' },
  { id: 'Bratislava', name: 'Bratislava', flag: '🇸🇰' },
  { id: 'Vilnius', name: 'Vilnius', flag: '🇱🇹' },
  { id: 'Riga', name: 'Riga', flag: '🇱🇻' },
  { id: 'Tallinn', name: 'Tallinn', flag: '🇪🇪' },
  { id: 'Reykjavik', name: 'Reykjavik', flag: '🇮🇸' },
  { id: 'Luxembourg', name: 'Luxembourg', flag: '🇱🇺' },
  { id: 'Valletta', name: 'Valletta', flag: '🇲🇹' },
  { id: 'Nicosia', name: 'Nicosia', flag: '🇨🇾' },
  { id: 'Islamabad', name: 'Islamabad', flag: '🇵🇰' },
  { id: 'Dhaka', name: 'Dhaka', flag: '🇧🇩' },
  { id: 'Colombo', name: 'Colombo', flag: '🇱🇰' },
  { id: 'Kathmandu', name: 'Kathmandu', flag: '🇳🇵' },
  { id: 'Naypyidaw', name: 'Naypyidaw', flag: '🇲🇲' },
  { id: 'Phnom Penh', name: 'Phnom Penh', flag: '🇰🇭' },
  { id: 'Vientiane', name: 'Vientiane', flag: '🇱🇦' },
  { id: 'Ulaanbaatar', name: 'Ulaanbaatar', flag: '🇲🇳' },
  { id: 'Nur-Sultan', name: 'Nur-Sultan', flag: '🇰🇿' },
  { id: 'Tashkent', name: 'Tashkent', flag: '🇺🇿' },
  { id: 'Hong Kong', name: 'Hong Kong', flag: '🇭🇰' },
  { id: 'Taipei', name: 'Taipei', flag: '🇹🇼' },
  { id: 'Macau', name: 'Macau', flag: '🇲🇴' },
  { id: 'Beirut', name: 'Beirut', flag: '🇱🇧' },
  { id: 'Amman', name: 'Amman', flag: '🇯🇴' },
  { id: 'Kuwait City', name: 'Kuwait City', flag: '🇰🇼' },
  { id: 'Manama', name: 'Manama', flag: '🇧🇭' },
  { id: 'Muscat', name: 'Muscat', flag: '🇴🇲' },
  { id: "Sana'a", name: "Sana'a", flag: '🇾🇪' },
  { id: 'Baghdad', name: 'Baghdad', flag: '🇮🇶' },
  { id: 'Tehran', name: 'Tehran', flag: '🇮🇷' },
  { id: 'Kabul', name: 'Kabul', flag: '🇦🇫' },
  { id: 'Baku', name: 'Baku', flag: '🇦🇿' },
  { id: 'Tbilisi', name: 'Tbilisi', flag: '🇬🇪' },
  { id: 'Yerevan', name: 'Yerevan', flag: '🇦🇲' },
  { id: 'San Jose', name: 'San Jose', flag: '🇨🇷' },
  { id: 'Panama City', name: 'Panama City', flag: '🇵🇦' },
  { id: 'Quito', name: 'Quito', flag: '🇪🇨' },
  { id: 'La Paz', name: 'La Paz', flag: '🇧🇴' },
  { id: 'Asuncion', name: 'Asuncion', flag: '🇵🇾' },
  { id: 'Montevideo', name: 'Montevideo', flag: '🇺🇾' },
  { id: 'Caracas', name: 'Caracas', flag: '🇻🇪' },
  { id: 'Havana', name: 'Havana', flag: '🇨🇺' },
  { id: 'Santo Domingo', name: 'Santo Domingo', flag: '🇩🇴' },
  { id: 'Kingston', name: 'Kingston', flag: '🇯🇲' },
  { id: 'Port of Spain', name: 'Port of Spain', flag: '🇹🇹' },
  { id: 'Bridgetown', name: 'Bridgetown', flag: '🇧🇧' },
  { id: 'Nassau', name: 'Nassau', flag: '🇧' },
  { id: 'Suva', name: 'Suva', flag: '🇫🇯' },
  { id: 'Port Moresby', name: 'Port Moresby', flag: '🇵🇬' },
  { id: 'Male', name: 'Male', flag: '🇲🇻' },
  { id: 'Victoria', name: 'Victoria', flag: '🇸🇨' },
  { id: 'Port Louis', name: 'Port Louis', flag: '🇲🇺' },
  { id: 'Antananarivo', name: 'Antananarivo', flag: '🇲🇬' },
  { id: 'Bandar Seri Begawan', name: 'Bandar Seri Begawan', flag: '🇧🇳' },
  { id: 'Skopje', name: 'Skopje', flag: '🇲🇰' },
  { id: 'Sarajevo', name: 'Sarajevo', flag: '🇧🇦' },
  { id: 'Tirana', name: 'Tirana', flag: '🇦🇱' },
  { id: 'Podgorica', name: 'Podgorica', flag: '🇲🇪' },
  { id: 'Pristina', name: 'Pristina', flag: '🇽🇰' },
  { id: 'Chisinau', name: 'Chisinau', flag: '🇲🇩' },
  { id: 'Minsk', name: 'Minsk', flag: '🇧🇾' },
  { id: 'Guatemala City', name: 'Guatemala City', flag: '🇬🇹' },
  { id: 'Tegucigalpa', name: 'Tegucigalpa', flag: '🇭🇳' },
  { id: 'San Salvador', name: 'San Salvador', flag: '🇸🇻' },
  { id: 'Managua', name: 'Managua', flag: '🇳🇮' },
  { id: 'Belmopan', name: 'Belmopan', flag: '🇧🇿' },
  { id: 'Port-au-Prince', name: 'Port-au-Prince', flag: '🇭🇹' },
  { id: 'Georgetown', name: 'Georgetown', flag: '🇬🇾' },
  { id: 'Paramaribo', name: 'Paramaribo', flag: '🇸🇷' },
  { id: 'Cayenne', name: 'Cayenne', flag: '🇬🇫' },
  { id: 'Porto-Novo', name: 'Porto-Novo', flag: '🇧🇯' },
  { id: 'Ouagadougou', name: 'Ouagadougou', flag: '🇧🇫' },
  { id: 'Praia', name: 'Praia', flag: '🇨🇻' },
  { id: "N'Djamena", name: "N'Djamena", flag: '🇹🇩' },
  { id: 'Moroni', name: 'Moroni', flag: '🇰🇲' },
  { id: 'Brazzaville', name: 'Brazzaville', flag: '🇨🇬' },
  { id: 'Kinshasa', name: 'Kinshasa', flag: '🇨🇩' },
  { id: 'Djibouti', name: 'Djibouti', flag: '🇩' },
  { id: 'Malabo', name: 'Malabo', flag: '🇬🇶' },
  { id: 'Asmara', name: 'Asmara', flag: '🇪🇷' },
  { id: 'Libreville', name: 'Libreville', flag: '🇬🇦' },
  { id: 'Banjul', name: 'Banjul', flag: '🇬🇲' },
  { id: 'Conakry', name: 'Conakry', flag: '🇬🇳' },
  { id: 'Bissau', name: 'Bissau', flag: '🇬🇼' },
  { id: 'Maseru', name: 'Maseru', flag: '🇱🇸' },
  { id: 'Monrovia', name: 'Monrovia', flag: '🇱🇷' },
  { id: 'Lilongwe', name: 'Lilongwe', flag: '🇲🇼' },
  { id: 'Bamako', name: 'Bamako', flag: '🇲🇱' },
  { id: 'Nouakchott', name: 'Nouakchott', flag: '🇲🇷' },
  { id: 'Niamey', name: 'Niamey', flag: '🇳🇪' },
  { id: 'Saint-Denis', name: 'Saint-Denis', flag: '🇷🇪' },
  { id: 'Sao Tome', name: 'Sao Tome', flag: '🇸🇹' },
  { id: 'Freetown', name: 'Freetown', flag: '🇸🇱' },
  { id: 'Mogadishu', name: 'Mogadishu', flag: '🇸🇴' },
  { id: 'Juba', name: 'Juba', flag: '🇸🇸' },
  { id: 'Mbabane', name: 'Mbabane', flag: '🇸🇿' },
  { id: 'Lome', name: 'Lome', flag: '🇹🇬' },
  { id: 'Bujumbura', name: 'Bujumbura', flag: '🇧🇮' },
  { id: 'Bangui', name: 'Bangui', flag: '🇨🇫' },
];

export const liveCategories = [
  { id: 'all', name: 'All' },
  { id: 'entertainment', name: 'Entertainment' },
  { id: 'education', name: 'Education' },
  { id: 'culture', name: 'Culture' },
  { id: 'religion', name: 'Religion' },
  { id: 'business & tech', name: 'Business' },
  { id: 'sports & fitness', name: 'Sports' },
];
