import { Globe } from 'lucide-react';

export type LocationOption = {
  id: string;
  name: string;
  icon?: any;
};

export const locations: LocationOption[] = [
  { id: 'all', name: 'All Cities', icon: Globe },
  { id: 'Dar es Salaam', name: 'Dar es Salaam' },
  { id: 'Nairobi', name: 'Nairobi' },
  { id: 'New York', name: 'New York' },
  { id: 'London', name: 'London' },
  { id: 'Toronto', name: 'Toronto' },
  { id: 'Sydney', name: 'Sydney' },
  { id: 'Berlin', name: 'Berlin' },
  { id: 'Paris', name: 'Paris' },
  { id: 'Rome', name: 'Rome' },
  { id: 'Madrid', name: 'Madrid' },
  { id: 'Amsterdam', name: 'Amsterdam' },
  { id: 'Brussels', name: 'Brussels' },
  { id: 'Zurich', name: 'Zurich' },
  { id: 'Vienna', name: 'Vienna' },
  { id: 'Stockholm', name: 'Stockholm' },
  { id: 'Oslo', name: 'Oslo' },
  { id: 'Copenhagen', name: 'Copenhagen' },
  { id: 'Helsinki', name: 'Helsinki' },
  { id: 'Warsaw', name: 'Warsaw' },
  { id: 'Lisbon', name: 'Lisbon' },
  { id: 'Athens', name: 'Athens' },
  { id: 'Prague', name: 'Prague' },
  { id: 'Dublin', name: 'Dublin' },
  { id: 'Tokyo', name: 'Tokyo' },
  { id: 'Seoul', name: 'Seoul' },
  { id: 'Beijing', name: 'Beijing' },
  { id: 'Mumbai', name: 'Mumbai' },
  { id: 'Singapore', name: 'Singapore' },
  { id: 'Bangkok', name: 'Bangkok' },
  { id: 'Kuala Lumpur', name: 'Kuala Lumpur' },
  { id: 'Jakarta', name: 'Jakarta' },
  { id: 'Manila', name: 'Manila' },
  { id: 'Hanoi', name: 'Hanoi' },
  { id: 'Dubai', name: 'Dubai' },
  { id: 'Riyadh', name: 'Riyadh' },
  { id: 'Doha', name: 'Doha' },
  { id: 'Jerusalem', name: 'Jerusalem' },
  { id: 'Istanbul', name: 'Istanbul' },
  { id: 'Rio de Janeiro', name: 'Rio de Janeiro' },
  { id: 'Buenos Aires', name: 'Buenos Aires' },
  { id: 'Mexico City', name: 'Mexico City' },
  { id: 'Bogota', name: 'Bogota' },
  { id: 'Santiago', name: 'Santiago' },
  { id: 'Lima', name: 'Lima' },
  { id: 'Cape Town', name: 'Cape Town' },
  { id: 'Lagos', name: 'Lagos' },
  { id: 'Cairo', name: 'Cairo' },
  { id: 'Casablanca', name: 'Casablanca' },
  { id: 'Accra', name: 'Accra' },
  { id: 'Addis Ababa', name: 'Addis Ababa' },
  { id: 'Kampala', name: 'Kampala' },
  { id: 'Kigali', name: 'Kigali' },
  { id: 'Lusaka', name: 'Lusaka' },
  { id: 'Harare', name: 'Harare' },
  { id: 'Gaborone', name: 'Gaborone' },
  { id: 'Windhoek', name: 'Windhoek' },
  { id: 'Maputo', name: 'Maputo' },
  { id: 'Luanda', name: 'Luanda' },
  { id: 'Dakar', name: 'Dakar' },
  { id: 'Abidjan', name: 'Abidjan' },
  { id: 'Yaounde', name: 'Yaounde' },
  { id: 'Algiers', name: 'Algiers' },
  { id: 'Tunis', name: 'Tunis' },
  { id: 'Tripoli', name: 'Tripoli' },
  { id: 'Khartoum', name: 'Khartoum' },
  { id: 'Wellington', name: 'Wellington' },
  { id: 'Moscow', name: 'Moscow' },
  { id: 'Kyiv', name: 'Kyiv' },
  { id: 'Budapest', name: 'Budapest' },
  { id: 'Bucharest', name: 'Bucharest' },
  { id: 'Sofia', name: 'Sofia' },
  { id: 'Zagreb', name: 'Zagreb' },
  { id: 'Belgrade', name: 'Belgrade' },
  { id: 'Ljubljana', name: 'Ljubljana' },
  { id: 'Bratislava', name: 'Bratislava' },
  { id: 'Vilnius', name: 'Vilnius' },
  { id: 'Riga', name: 'Riga' },
  { id: 'Tallinn', name: 'Tallinn' },
  { id: 'Reykjavik', name: 'Reykjavik' },
  { id: 'Luxembourg', name: 'Luxembourg' },
  { id: 'Valletta', name: 'Valletta' },
  { id: 'Nicosia', name: 'Nicosia' },
  { id: 'Islamabad', name: 'Islamabad' },
  { id: 'Dhaka', name: 'Dhaka' },
  { id: 'Colombo', name: 'Colombo' },
  { id: 'Kathmandu', name: 'Kathmandu' },
  { id: 'Naypyidaw', name: 'Naypyidaw' },
  { id: 'Phnom Penh', name: 'Phnom Penh' },
  { id: 'Vientiane', name: 'Vientiane' },
  { id: 'Ulaanbaatar', name: 'Ulaanbaatar' },
  { id: 'Nur-Sultan', name: 'Nur-Sultan' },
  { id: 'Tashkent', name: 'Tashkent' },
  { id: 'Hong Kong', name: 'Hong Kong' },
  { id: 'Taipei', name: 'Taipei' },
  { id: 'Macau', name: 'Macau' },
  { id: 'Beirut', name: 'Beirut' },
  { id: 'Amman', name: 'Amman' },
  { id: 'Kuwait City', name: 'Kuwait City' },
  { id: 'Manama', name: 'Manama' },
  { id: 'Muscat', name: 'Muscat' },
  { id: "Sana'a", name: "Sana'a" },
  { id: 'Baghdad', name: 'Baghdad' },
  { id: 'Tehran', name: 'Tehran' },
  { id: 'Kabul', name: 'Kabul' },
  { id: 'Baku', name: 'Baku' },
  { id: 'Tbilisi', name: 'Tbilisi' },
  { id: 'Yerevan', name: 'Yerevan' },
  { id: 'San Jose', name: 'San Jose' },
  { id: 'Panama City', name: 'Panama City' },
  { id: 'Quito', name: 'Quito' },
  { id: 'La Paz', name: 'La Paz' },
  { id: 'Asuncion', name: 'Asuncion' },
  { id: 'Montevideo', name: 'Montevideo' },
  { id: 'Caracas', name: 'Caracas' },
  { id: 'Havana', name: 'Havana' },
  { id: 'Santo Domingo', name: 'Santo Domingo' },
  { id: 'Kingston', name: 'Kingston' },
  { id: 'Port of Spain', name: 'Port of Spain' },
  { id: 'Bridgetown', name: 'Bridgetown' },
  { id: 'Nassau', name: 'Nassau' },
  { id: 'Suva', name: 'Suva' },
  { id: 'Port Moresby', name: 'Port Moresby' },
  { id: 'Male', name: 'Male' },
  { id: 'Victoria', name: 'Victoria' },
  { id: 'Port Louis', name: 'Port Louis' },
  { id: 'Antananarivo', name: 'Antananarivo' },
  { id: 'Bandar Seri Begawan', name: 'Bandar Seri Begawan' },
  { id: 'Skopje', name: 'Skopje' },
  { id: 'Sarajevo', name: 'Sarajevo' },
  { id: 'Tirana', name: 'Tirana' },
  { id: 'Podgorica', name: 'Podgorica' },
  { id: 'Pristina', name: 'Pristina' },
  { id: 'Chisinau', name: 'Chisinau' },
  { id: 'Minsk', name: 'Minsk' },
  { id: 'Guatemala City', name: 'Guatemala City' },
  { id: 'Tegucigalpa', name: 'Tegucigalpa' },
  { id: 'San Salvador', name: 'San Salvador' },
  { id: 'Managua', name: 'Managua' },
  { id: 'Belmopan', name: 'Belmopan' },
  { id: 'Port-au-Prince', name: 'Port-au-Prince' },
  { id: 'Georgetown', name: 'Georgetown' },
  { id: 'Paramaribo', name: 'Paramaribo' },
  { id: 'Cayenne', name: 'Cayenne' },
  { id: 'Porto-Novo', name: 'Porto-Novo' },
  { id: 'Ouagadougou', name: 'Ouagadougou' },
  { id: 'Praia', name: 'Praia' },
  { id: "N'Djamena", name: "N'Djamena" },
  { id: 'Moroni', name: 'Moroni' },
  { id: 'Brazzaville', name: 'Brazzaville' },
  { id: 'Kinshasa', name: 'Kinshasa' },
  { id: 'Djibouti', name: 'Djibouti' },
  { id: 'Malabo', name: 'Malabo' },
  { id: 'Asmara', name: 'Asmara' },
  { id: 'Libreville', name: 'Libreville' },
  { id: 'Banjul', name: 'Banjul' },
  { id: 'Conakry', name: 'Conakry' },
  { id: 'Bissau', name: 'Bissau' },
  { id: 'Maseru', name: 'Maseru' },
  { id: 'Monrovia', name: 'Monrovia' },
  { id: 'Lilongwe', name: 'Lilongwe' },
  { id: 'Bamako', name: 'Bamako' },
  { id: 'Nouakchott', name: 'Nouakchott' },
  { id: 'Niamey', name: 'Niamey' },
  { id: 'Saint-Denis', name: 'Saint-Denis' },
  { id: 'Sao Tome', name: 'Sao Tome' },
  { id: 'Freetown', name: 'Freetown' },
  { id: 'Mogadishu', name: 'Mogadishu' },
  { id: 'Juba', name: 'Juba' },
  { id: 'Mbabane', name: 'Mbabane' },
  { id: 'Lome', name: 'Lome' },
  { id: 'Bujumbura', name: 'Bujumbura' },
  { id: 'Bangui', name: 'Bangui' },
];

export const liveCategories = [
  { id: 'all', name: 'All' },
  { id: 'entertainment', name: 'Entertainment' },
  { id: 'education', name: 'Education' },
  { id: 'culture', name: 'Culture' },
  { id: 'religion', name: 'Religion' },
  { id: 'business & tech', name: 'Business' },
  { id: 'sports & fitness', name: 'Sports' },
];
